// Sinhala text for the app, keyed by the English text (see i18n.dart).
// Shared with the web app's frontend/src/locales/si.json, plus mobile-only strings.
const Map<String, String> siStrings = {
  "\" yet.": "\" සඳහා.",
  "\" 🟡 Cheapest 🔴 Other suppliers 🔵 Delivery location":
      "\" 🟡 අඩුම මිල 🔴 වෙනත් සැපයුම්කරුවන් 🔵 බෙදාහැරීමේ ස්ථානය",
  "% of floor": "% අවම සීමාවෙන්",
  "'s": "ගේ",
  "(based on": "(පදනම",
  "(for items they carry)": "(ඔවුන් සපයන භාණ්ඩ සඳහා)",
  "+ Add Item": "+ භාණ්ඩයක් එක් කරන්න",
  "+ Add Supplier": "+ සැපයුම්කරුවෙකු එක් කරන්න",
  "+ Add item": "+ භාණ්ඩයක් එක් කරන්න",
  "+ New Decision": "+ නව තීරණයක්",
  "+ New Transaction": "+ නව ගනුදෙනුවක්",
  "-day delivery": "-දින බෙදාහැරීම",
  "-day lead time)": "-දින බෙදාහැරීමේ කාලය)",
  "/day": "/දිනකට",
  "/week forecast": "/සතියට පුරෝකථනය",
  "21.7% more accurate than “same as last week”": "“පසුගිය සතිය හා සමානයි” යන්නට වඩා 21.7% නිවැරදියි",
  "6 models · Linear Regression · K-Means · Demand Index":
      "මාදිලි 6 · Linear Regression · K-Means · Demand Index",
  "64% better right after Avurudu. Usually off by about 11 units a week.":
      "අවුරුද්දට පසු 64% හොඳයි. සාමාන්‍යයෙන් සතියකට ඒකක 11ක් පමණ වෙනස් වේ.",
  "7-day and 14-day moving averages. % change over full period.":
      "දින 7 සහ දින 14 චලන සාමාන්‍ය. සම්පූර්ණ කාලය තුළ % වෙනස.",
  "7-day velocity:": "දින 7 වේගය:",
  "A quick snapshot of your income, expenses and stock — plus fast access to everything you manage.":
      "ඔබේ ආදායම, වියදම් සහ තොගය පිළිබඳ කෙටි දළ විශ්ලේෂණයක් — ඔබ කළමනාකරණය කරන සියල්ලට ඉක්මන් ප්‍රවේශය සමඟ.",
  "A thin margin hurts — check your prices and cut waste.":
      "අඩු ලාභ ආන්තිකයක් හානිකරයි — මිල පරීක්ෂා කර නාස්තිය අඩු කරන්න.",
  "AI insights": "AI අවබෝධය",
  "AI you can check": "ඔබට පරීක්ෂා කළ හැකි AI",
  "About": "පිළිබඳ",
  "Above floor ✓": "අවම සීමාවට ඉහළින් ✓",
  "Account": "ගිණුම",
  "Account Activity": "ගිණුම් ක්‍රියාකාරකම්",
  "Account Details": "ගිණුම් විස්තර",
  "Account ID": "ගිණුම් අංකය",
  "Account Number": "ගිණුම් අංකය",
  "Account Number *": "ගිණුම් අංකය *",
  "Account number is required.": "ගිණුම් අංකය අවශ්‍යයි.",
  "Account safety": "ගිණුම් ආරක්ෂාව",
  "Accounting": "ගිණුම්කරණය",
  "Action": "ක්‍රියාව",
  "Active": "සක්‍රිය",
  "Add": "එක් කරන්න",
  "Add Bank": "බැංකුවක් එක් කරන්න",
  "Add Cash": "මුදල් එක් කරන්න",
  "Add Cash to Pool": "සංචිතයට මුදල් එක් කරන්න",
  "Add Inventory": "තොගය එක් කරන්න",
  "Add Inventory Item": "තොග භාණ්ඩයක් එක් කරන්න",
  "Add Item": "භාණ්ඩයක් එක් කරන්න",
  "Add Supplier": "සැපයුම්කරුවෙකු එක් කරන්න",
  "Add a bank in 'My Banks' first": "මුලින්ම 'මගේ බැංකු' තුළ බැංකුවක් එක් කරන්න",
  "Add a new stock item.": "නව තොග භාණ්ඩයක් එක් කරන්න.",
  "Add at least one item.": "අවම වශයෙන් එක් භාණ්ඩයක් එක් කරන්න.",
  "Add optional note for sale/purchase...": "විකුණුම/මිලදී ගැනීම සඳහා සටහනක් (අවශ්‍ය නම්)...",
  "Add optional note...": "සටහනක් එක් කරන්න (අවශ්‍ය නම්)...",
  "Add physical cash you've brought into the drawer (e.g. withdrawn from a bank). This increases your shared cash pool.":
      "ලාච්චුවට ගෙනා මුදල් එක් කරන්න (උදා. බැංකුවෙන් ගත් මුදල්). මෙයින් ඔබේ පොදු මුදල් සංචිතය වැඩි වේ.",
  "Add your first stock item.": "ඔබේ පළමු තොග භාණ්ඩය එක් කරන්න.",
  "Add your first supplier.": "ඔබේ පළමු සැපයුම්කරු එක් කරන්න.",
  "Add your first transaction.": "ඔබේ පළමු ගනුදෙනුව එක් කරන්න.",
  "Added items": "එක් කළ භාණ්ඩ",
  "Address (auto-filled from the map — edit if needed)":
      "ලිපිනය (සිතියමෙන් ස්වයංක්‍රීයව — අවශ්‍ය නම් වෙනස් කරන්න)",
  "Admin": "පරිපාලක",
  "Admin Actions": "පරිපාලක ක්‍රියා",
  "Admin Dashboard": "පරිපාලක උපකරණ පුවරුව",
  "After adding": "එක් කළ පසු",
  "After top-up": "පිරවීමෙන් පසු",
  "Agency Banking": "නියෝජිත බැංකුකරණය",
  "Agency Banking Report": "නියෝජිත බැංකු වාර්තාව",
  "Agency Banking — Today": "නියෝජිත බැංකුකරණය — අද",
  "Agency Commission": "නියෝජිත කොමිස්",
  "Agency Summary": "නියෝජිත සාරාංශය",
  "Agency banking performance and business overview.": "නියෝජිත බැංකු කාර්ය සාධනය සහ ව්‍යාපාර දළ විශ්ලේෂණය.",
  "Agent Bank (Float Account)": "නියෝජිත බැංකුව (float ගිණුම)",
  "Alert threshold (Auto-calculated by AI if empty)": "ඇඟවීම් සීමාව (හිස් නම් AI මගින් ගණනය කෙරේ)",
  "Alerts from inventory, procurement, ledger, and agency banking modules.":
      "තොග, මිලදී ගැනීම්, ලෙජරය සහ නියෝජිත බැංකු මොඩියුලවලින් ඇඟවීම්.",
  "All (": "සියල්ල (",
  "All Items — Sales Summary": "සියලු භාණ්ඩ — විකුණුම් සාරාංශය",
  "All Items — Stock Status": "සියලු භාණ්ඩ — තොග තත්ත්වය",
  "All Transactions": "සියලු ගනුදෙනු",
  "All financial transactions.": "සියලු මූල්‍ය ගනුදෙනු.",
  "All stock healthy": "සියලු තොග හොඳ මට්ටමේ",
  "Already have an account?": "දැනටමත් ගිණුමක් තිබේද?",
  "Amount": "මුදල",
  "Amount (LKR)": "මුදල (රු.)",
  "Amount (LKR) *": "මුදල (රු.) *",
  "Amount Abs Rs": "ගනුදෙනු මුදල",
  "Amount Z-score": "මුදලේ Z-ලකුණ",
  "Amount Zscore": "සාමාන්‍යයට සාපේක්ෂ මුදල",
  "Amount vs usual": "සාමාන්‍යයට සාපේක්ෂ මුදල",
  "Ampara": "අම්පාර",
  "Analysing suppliers...": "සැපයුම්කරුවන් විශ්ලේෂණය කරමින්...",
  "Analysing...": "විශ්ලේෂණය කරමින්...",
  "Anuradhapura": "අනුරාධපුරය",
  "App Version": "යෙදුමේ අනුවාදය",
  "Appearance": "පෙනුම",
  "Apply": "යොදන්න",
  "Apr": "අප්‍රේ",
  "Arrival Date *": "පැමිණෙන දිනය *",
  "As of": "දිනට",
  "At least 6 characters": "අවම අක්ෂර 6ක්",
  "Aug": "අගෝ",
  "Auto-calculated from items — editable": "භාණ්ඩවලින් ස්වයංක්‍රීයව ගණනය — වෙනස් කළ හැක",
  "Auto-filled from amount — you can change it": "මුදලින් ස්වයංක්‍රීයව — ඔබට වෙනස් කළ හැක",
  "Auto-filled from inventory cost — editable": "තොග පිරිවැයෙන් ස්වයංක්‍රීයව පිරවේ — වෙනස් කළ හැක",
  "Available": "ලබාගත හැක",
  "Available Quantity": "ලබාගත හැකි ප්‍රමාණය",
  "Available for Top-up": "පිරවීමට ඇති මුදල",
  "Available to top up": "පිරවීමට ඇති මුදල",
  "Average Daily Transactions": "සාමාන්‍ය දෛනික ගනුදෙනු",
  "Avg Daily Txns": "දෛනික සාමාන්‍ය ගනුදෙනු",
  "Avg Retail Price": "සාමාන්‍ය සිල්ලර මිල",
  "Avg Retail Price (LKR)": "සාමාන්‍ය සිල්ලර මිල (රු.)",
  "Avg Sale Price": "සාමාන්‍ය විකුණුම් මිල",
  "Avg Wholesale Price": "සාමාන්‍ය තොග මිල",
  "Avg Wholesale Price (LKR)": "සාමාන්‍ය තොග මිල (රු.)",
  "Avg. Unit Cost": "සාමාන්‍ය ඒකක පිරිවැය",
  "Avg. delivery cost": "සාමාන්‍ය බෙදාහැරීමේ ගාස්තුව",
  "Avurudu-aware forecasts": "අවුරුදු සලකන පුරෝකථන",
  "Ayubowan 👋": "ආයුබෝවන් 👋",
  "Back": "ආපසු",
  "Back to Sign In": "පිවිසුමට ආපසු",
  "Badulla": "බදුල්ල",
  "Bal:": "ශේෂය:",
  "Balance Inquiry": "ශේෂ විමසීම",
  "Balanced ✓": "සමතුලිතයි ✓",
  "Bank": "බැංකුව",
  "Bank Agent": "බැංකු නියෝජිත",
  "Bank Agent Dashboard": "බැංකු නියෝජිත උපකරණ පුවරුව",
  "Bank Agents": "බැංකු නියෝජිතයින්",
  "Bank Name": "බැංකුවේ නම",
  "Bank Name *": "බැංකුවේ නම *",
  "Bank agent payout": "බැංකු නියෝජිත ගෙවීම",
  "Bank name is required.": "බැංකුවේ නම අවශ්‍යයි.",
  "Banking Anomaly": "බැංකු අසාමාන්‍යතා",
  "Batticaloa": "මඩකලපුව",
  "Beats the usual bank rules: F1 0.75 vs 0.68": "සාමාන්‍ය බැංකු නීතිවලට වඩා හොඳයි: F1 0.75 එදිරිව 0.68",
  "Below floor": "අවම සීමාවට පහළින්",
  "Best delivery source per item": "එක් එක් භාණ්ඩයට හොඳම සැපයුම් ස්ථානය",
  "Best match": "වඩාත් ගැළපෙන",
  "Best match first, then the next-nearest suppliers for this order.":
      "මුලින් වඩාත් ගැළපෙන සැපයුම්කරු, ඉන්පසු මෙම ඇණවුමට ළඟම සැපයුම්කරුවන්.",
  "Best supplier for this order (": "මෙම ඇණවුමට හොඳම සැපයුම්කරු (",
  "Beverages": "බීම වර්ග",
  "Bill Payment": "බිල්පත් ගෙවීම",
  "Boost daily sales or profit margin to increase your eligibility score.":
      "සුදුසුකම් ලකුණු වැඩි කිරීමට දෛනික විකුණුම් හෝ ලාභ ආන්තිකය වැඩි කරන්න.",
  "Bought": "මිලදී ගත්",
  "Box": "පෙට්ටිය",
  "Built for rural Sri Lanka": "ග්‍රාමීය ශ්‍රී ලංකාව සඳහා නිර්මාණය කළා",
  "Business": "ව්‍යාපාරය",
  "Business Expense": "ව්‍යාපාර වියදම",
  "Business Income": "ව්‍යාපාර ආදායම",
  "Business Overview": "ව්‍යාපාර දළ විශ්ලේෂණය",
  "Buy": "මිලදී ගන්න",
  "Buy now or wait, from stock, forecast and price trend.":
      "තොගය, පුරෝකථනය සහ මිල ප්‍රවණතාව අනුව දැන් ගන්නද රැඳී සිටින්නද.",
  "Buy or Wait": "ගන්නද රැඳී සිටින්නද",
  "Buy when stock falls below what the forecast needs until delivery.":
      "බෙදාහැරීම දක්වා අවශ්‍ය ප්‍රමාණයට වඩා තොගය අඩු වූ විට මිලදී ගන්න.",
  "Buying price per unit": "ඒකකයක මිලදී ගැනීමේ මිල",
  "Buying price per unit (goes to the batch cost)": "ඒකකයක මිලදී ගැනීමේ මිල (කාණ්ඩ පිරිවැයට යයි)",
  "CBSL Daily Limits:": "CBSL දෛනික සීමා:",
  "CBSL limits are always enforced; the model catches what the limits cannot.":
      "CBSL සීමා සැමවිටම බලාත්මකයි; සීමාවලට අල්ලාගත නොහැකි දේ මාදිලිය හඳුනාගනී.",
  "CBSL limits are hard rules that are always enforced. The models flag what rules cannot see.":
      "CBSL සීමා සැමවිටම බලාත්මක වන දැඩි නීති වේ. නීතිවලට නොපෙනෙන දේ මාදිලි හඳුනාගනී.",
  "CBSL limits built in": "CBSL සීමා ඇතුළත්",
  "CRITICAL": "බරපතළ",
  "Calculating...": "ගණනය කරමින්...",
  "Cancel": "අවලංගු කරන්න",
  "Cancelled": "අවලංගුයි",
  "Canned & Packaged Food": "ටින් සහ ඇසුරුම් කළ ආහාර",
  "Card, QR and bank payments build a record that banks trust.":
      "කාඩ්, QR සහ බැංකු ගෙවීම් බැංකු විශ්වාස කරන වාර්තාවක් ගොඩනගයි.",
  "Carries:": "සපයන්නේ:",
  "Carton": "කාටනය",
  "Cash": "මුදල්",
  "Cash Amount (LKR)": "මුදල් ප්‍රමාණය (රු.)",
  "Cash Deposit": "මුදල් තැන්පතුව",
  "Cash Deposit LKR 50,000 · Cash Withdrawal LKR 25,000 · Fund Transfer LKR 100,000":
      "මුදල් තැන්පතු රු. 50,000 · මුදල් ආපසු ගැනීම රු. 25,000 · අරමුදල් මාරු කිරීම රු. 100,000",
  "Cash Flow Margin": "මුදල් ප්‍රවාහ ආන්තිකය",
  "Cash Withdrawal": "මුදල් ආපසු ගැනීම",
  "Cash after": "පසු මුදල්",
  "Cash isn't allowed for Transfer transactions.": "මාරු කිරීමේ ගනුදෙනු සඳහා මුදල් (cash) භාවිත කළ නොහැක.",
  "Cash isn't available for transfers": "මාරු කිරීම් සඳහා මුදල් (cash) භාවිත කළ නොහැක",
  "Cash on Hand": "අතේ ඇති මුදල්",
  "Cash on Hand (shared pool)": "අතේ ඇති මුදල් (පොදු සංචිතය)",
  "Cash on hand": "අතේ ඇති මුදල්",
  "Cash on hand (pool)": "අතේ ඇති මුදල් (සංචිතය)",
  "Cash withdrawal · LKR 50,000 — why:": "මුදල් ආපසු ගැනීම · රු. 50,000 — හේතුව:",
  "Category": "ප්‍රවර්ගය",
  "Category *": "ප්‍රවර්ගය *",
  "Ceiling:": "උපරිම සීමාව:",
  "Channel": "මාධ්‍යය",
  "Charged to the customer": "පාරිභෝගිකයාගෙන් අය කෙරේ",
  "Cheapest": "අඩුම මිල",
  "Cheapest:": "අඩුම මිල:",
  "Cheapest: LKR": "අඩුම මිල: රු.",
  "Check loan eligibility and financial risk profile.": "ණය සුදුසුකම සහ මූල්‍ය අවදානම පරීක්ෂා කරන්න.",
  "Check your email": "ඔබේ ඊමේල් පරීක්ෂා කරන්න",
  "Checking stock...": "තොගය පරීක්ෂා කරමින්...",
  "Choose a new password for your Lanka-Link account.": "ඔබේ Lanka-Link ගිණුමට නව මුරපදයක් තෝරන්න.",
  "Choose from your suppliers": "ඔබේ සැපයුම්කරුවන්ගෙන් තෝරන්න",
  "Clear": "මකන්න",
  "Colombo": "කොළඹ",
  "Commission": "කොමිස් මුදල",
  "Commission (LKR)": "කොමිස් (රු.)",
  "Company": "සමාගම",
  "Company Name": "සමාගමේ නම",
  "Completed": "සම්පූර්ණයි",
  "Component 2 — predict units of demand for an item.": "සංරචකය 2 — භාණ්ඩයක ඉල්ලුම් ඒකක පුරෝකථනය කරන්න.",
  "Component 4 — flag suspicious transactions.": "සංරචකය 4 — සැක සහිත ගනුදෙනු හඳුනාගන්න.",
  "Conditional approval": "කොන්දේසි සහිත අනුමැතිය",
  "Confirm": "තහවුරු කරන්න",
  "Confirm new password": "නව මුරපදය තහවුරු කරන්න",
  "Contact": "සම්බන්ධතා",
  "Contact Number": "දුරකථන අංකය",
  "Contact Number *": "දුරකථන අංකය *",
  "Contact Number is required.": "දුරකථන අංකය අවශ්‍යයි.",
  "Contact number is required.": "දුරකථන අංකය අවශ්‍යයි.",
  "Contacts, delivery cost and lead time of every supplier.":
      "සෑම සැපයුම්කරුවෙකුගේම සම්බන්ධතා, බෙදාහැරීමේ ගාස්තුව සහ කාලය.",
  "Continue": "ඉදිරියට",
  "Cost / Selling Price per Unit (LKR)": "ඒකකයක පිරිවැය / විකුණුම් මිල (රු.)",
  "Cost Price per Unit (LKR)": "ඒකකයක පිරිවැය මිල (රු.)",
  "Cost Range": "පිරිවැය පරාසය",
  "Cost of Goods Sold": "විකුණූ භාණ්ඩවල පිරිවැය",
  "Cost of Goods Sold (Purchases)": "විකුණූ භාණ්ඩවල පිරිවැය (මිලදී ගැනීම්)",
  "Cost price cannot be negative.": "පිරිවැය මිල සෘණ විය නොහැක.",
  "Cost:": "පිරිවැය:",
  "Couldn't fetch route": "මාර්ගය ලබාගත නොහැකි විය",
  "Couldn't get your location.": "ඔබේ ස්ථානය ලබාගත නොහැකි විය.",
  "Couldn't get your location. Try picking it on the map instead.":
      "ඔබේ ස්ථානය ලබාගත නොහැකි විය. සිතියමෙන් තෝරන්න.",
  "Couldn't load Google Maps. Check the API key.": "Google Maps පූරණය කළ නොහැකි විය. API යතුර පරීක්ෂා කරන්න.",
  "Couldn't look up that place.": "එම ස්ථානය සොයාගත නොහැකි විය.",
  "Create": "සාදන්න",
  "Create Account": "ගිණුම සාදන්න",
  "Create a password": "මුරපදයක් සාදන්න",
  "Create account": "ගිණුමක් සාදන්න",
  "Create an account": "ගිණුමක් සාදන්න",
  "Create an account and start recording your sales today.":
      "ගිණුමක් සාදා අදම ඔබේ විකුණුම් සටහන් කිරීම අරඹන්න.",
  "Create your first decision.": "ඔබේ පළමු තීරණය සාදන්න.",
  "Created Offline": "නොබැඳිව සෑදූ",
  "Created Offline (0/1)": "නොබැඳිව සෑදූ (0/1)",
  "Creating account…": "ගිණුම සාදමින්…",
  "Credit": "බැර",
  "Credit (money in)": "බැර (මුදල් ලැබීම)",
  "Credit Readiness Assessment": "ණය සූදානම් ඇගයීම",
  "Credit Sales Ratio": "ණයට විකුණුම් අනුපාතය",
  "Credit Sales Ratio (0 - 1)": "ණයට විකුණුම් අනුපාතය (0 - 1)",
  "Credit Score": "ණය ලකුණු",
  "Credit score": "ණය ලකුණු",
  "Credit-readiness score and a loan limit from your net cash flow.":
      "ඔබේ ශුද්ධ මුදල් ප්‍රවාහයෙන් ණය සූදානම් ලකුණු සහ ණය සීමාව.",
  "Credit/Debit": "බැර/හර",
  "Critical": "බරපතළ",
  "Crunching your numbers...": "ඔබේ දත්ත ගණනය කරමින්...",
  "Current Price Rs": "වත්මන් මිල",
  "Current Qty": "වත්මන් ප්‍රමාණය",
  "Current Stock Kg": "වත්මන් තොගය (kg)",
  "Current cash pool": "වත්මන් මුදල් සංචිතය",
  "Current float": "වත්මන් float ශේෂය",
  "Current stock": "වත්මන් තොගය",
  "Current stock, its value and what needs reordering.":
      "වත්මන් තොගය, එහි වටිනාකම සහ නැවත ඇණවුම් කළ යුතු දේ.",
  "Current: LKR": "වත්මන්: රු.",
  "Custom": "අභිරුචි",
  "Customer": "පාරිභෝගිකයා",
  "Customer NIC": "පාරිභෝගික ජා.හැ.අ.",
  "Customer Name": "පාරිභෝගිකයාගේ නම",
  "Customer Name *": "පාරිභෝගිකයාගේ නම *",
  "Customer Name is required.": "පාරිභෝගිකයාගේ නම අවශ්‍යයි.",
  "Customer Phone": "පාරිභෝගික දුරකථනය",
  "Customer Phone *": "පාරිභෝගික දුරකථනය *",
  "Customer Phone is required.": "පාරිභෝගික දුරකථනය අවශ්‍යයි.",
  "Customer banking transactions and commission.": "පාරිභෝගික බැංකු ගනුදෙනු සහ කොමිස්.",
  "Customer deposit": "පාරිභෝගික තැන්පතුව",
  "Customer deposits, withdrawals and transfers with fees and commission.":
      "ගාස්තු සහ කොමිස් සමඟ පාරිභෝගික තැන්පතු, ආපසු ගැනීම් සහ මාරු කිරීම්.",
  "Customer name is required.": "පාරිභෝගිකයාගේ නම අවශ්‍යයි.",
  "Customer withdrawal": "පාරිභෝගික මුදල් ආපසු ගැනීම",
  "Cut monthly expenses by 10%": "මාසික වියදම් 10%කින් අඩු කරන්න",
  "Daily Sales": "දෛනික විකුණුම්",
  "Daily Summary": "දෛනික සාරාංශය",
  "Daily limit is": "දෛනික සීමාව",
  "Daily limit:": "දෛනික සීමාව:",
  "Daily sales count": "දෛනික විකුණුම් ගණන",
  "Daily transactions, journal and profit & loss.": "දෛනික ගනුදෙනු, ජර්නලය සහ ලාභ අලාභ.",
  "Dairy & Bakery": "කිරි සහ බේකරි",
  "Dark Mode": "අඳුරු ආකාරය",
  "Dark mode": "අඳුරු ආකාරය",
  "Dashboard": "උපකරණ පුවරුව",
  "Data: HKARTI · Models: Linear Regression · Moving Avg · K-Means · Demand Index":
      "දත්ත: HKARTI · මාදිලි: Linear Regression · Moving Avg · K-Means · Demand Index",
  "Date": "දිනය",
  "Date:": "දිනය:",
  "Day Of Month": "මාසයේ දිනය",
  "Day of Month": "මාසයේ දිනය",
  "Day of month": "මාසයේ දිනය",
  "Day total": "දින එකතුව",
  "Days To Avurudu": "අවුරුද්දට දින",
  "Days needed to deliver items (For AI Reorder Buffer)":
      "භාණ්ඩ බෙදාහැරීමට අවශ්‍ය දින (AI නැවත ඇණවුම් ගණනයට)",
  "Days to Avurudu": "අවුරුද්දට දින",
  "Debit": "හර",
  "Debit (money out)": "හර (මුදල් යැවීම)",
  "Debit and credit totals per account — both sides must match.":
      "එක් එක් ගිණුමේ හර සහ බැර එකතුව — දෙපැත්තම සමාන විය යුතුයි.",
  "Debt To Income": "ණය-ආදායම් අනුපාතය",
  "Debt To Income Ratio": "ණය-ආදායම් අනුපාතය",
  "Debt-to-Income Ratio": "ණය-ආදායම් අනුපාතය",
  "Dec": "දෙසැ",
  "Decision / Outcome": "තීරණය / ප්‍රතිඵලය",
  "Default: Auto AI": "පෙරනිමිය: AI ස්වයංක්‍රීය",
  "Deficit": "හිඟය",
  "Delete": "මකන්න",
  "Delete this notification?": "මෙම දැනුම්දීම මකන්නද?",
  "Delete this supplier?": "මෙම සැපයුම්කරු මකන්නද?",
  "Delete?": "මකන්නද?",
  "Delivery Cost (LKR)": "බෙදාහැරීමේ ගාස්තුව (රු.)",
  "Delivery Lead Time (Days)": "බෙදාහැරීමේ කාලය (දින)",
  "Delivery Location": "බෙදාහැරීමේ ස්ථානය",
  "Delivery Location *": "බෙදාහැරීමේ ස්ථානය *",
  "Delivery Optimization": "බෙදාහැරීම ප්‍රශස්තකරණය",
  "Delivery cost cannot be negative.": "බෙදාහැරීමේ ගාස්තුව සෘණ විය නොහැක.",
  "Demand Forecast": "ඉල්ලුම් පුරෝකථනය",
  "Demand Forecasting": "ඉල්ලුම් පුරෝකථනය",
  "Deposit": "තැන්පතුව",
  "Deposit must be paid via Cash.": "තැන්පතු මුදලින් (cash) ගෙවිය යුතුයි.",
  "Deposits & withdrawals": "තැන්පතු සහ ආපසු ගැනීම්",
  "Deposits are always Cash": "තැන්පතු සැමවිටම මුදලින්",
  "Deposits, withdrawals and transfers for partner banks.":
      "හවුල්කාර බැංකු සඳහා තැන්පතු, ආපසු ගැනීම් සහ මාරු කිරීම්.",
  "Describe the source of funds": "අරමුදල් මූලාශ්‍රය විස්තර කරන්න",
  "Description": "විස්තරය",
  "Description / Note": "විස්තරය / සටහන",
  "Details": "විස්තර",
  "Digital": "ඩිජිටල්",
  "Digital Payment Ratio": "ඩිජිටල් ගෙවීම් අනුපාතය",
  "Digital Payment Ratio (0 - 1)": "ඩිජිටල් ගෙවීම් අනුපාතය (0 - 1)",
  "Digital Revenue Volume": "ඩිජිටල් ආදායම් පරිමාව",
  "Digital Revenue Volume (LKR)": "ඩිජිටල් ආදායම් පරිමාව (රු.)",
  "Direction": "දිශාව",
  "Do this next": "ඊළඟට මෙය කරන්න",
  "Double-entry ledger": "ද්විත්ව සටහන් ලෙජරය",
  "Double-entry records (Debit / Credit) for every transaction.": "සෑම ගනුදෙනුවකටම ද්විත්ව සටහන් (හර / බැර).",
  "Double-entry records, goods movement and profit / loss.":
      "ද්විත්ව සටහන් වාර්තා, භාණ්ඩ චලනය සහ ලාභ / අලාභ.",
  "Download PDF": "PDF බාගන්න",
  "Drop all PDFs here or click to browse": "සියලු PDF මෙහි දමන්න හෝ තෝරා ගැනීමට ක්ලික් කරන්න",
  "Each model was tested on data it had never seen and compared with a simple rule.":
      "සෑම මාදිලියක්ම කවදාවත් නොදුටු දත්ත මත පරීක්ෂා කර සරල නීතියක් සමඟ සංසන්දනය කරන ලදී.",
  "Edit": "සංස්කරණය",
  "Edit Inventory Item": "තොග භාණ්ඩය සංස්කරණය",
  "Edit Procurement": "මිලදී ගැනීම සංස්කරණය",
  "Edit Profile": "පැතිකඩ සංස්කරණය",
  "Edit Supplier": "සැපයුම්කරු සංස්කරණය",
  "Edit Transaction": "ගනුදෙනුව සංස්කරණය",
  "Email": "ඊමේල්",
  "Email Address": "ඊමේල් ලිපිනය",
  "Enough stock.": "ප්‍රමාණවත් තොගයක් ඇත.",
  "Enter a valid Sri Lankan number.": "වලංගු ශ්‍රී ලංකා දුරකථන අංකයක් ඇතුළත් කරන්න.",
  "Enter a valid contact number (e.g. 0771234567).": "වලංගු දුරකථන අංකයක් ඇතුළත් කරන්න (උදා. 0771234567).",
  "Enter a valid email address.": "වලංගු ඊමේල් ලිපිනයක් ඇතුළත් කරන්න.",
  "Enter a valid phone number (10 digits).": "වලංගු දුරකථන අංකයක් ඇතුළත් කරන්න (ඉලක්කම් 10).",
  "Enter a valid quantity (0 or more).": "වලංගු ප්‍රමාණයක් ඇතුළත් කරන්න (0 හෝ වැඩි).",
  "Enter a valid quantity.": "වලංගු ප්‍රමාණයක් ඇතුළත් කරන්න.",
  "Enter an amount greater than 0.": "0ට වැඩි මුදලක් ඇතුළත් කරන්න.",
  "Enter company name": "සමාගමේ නම ඇතුළත් කරන්න",
  "Enter customer full name": "පාරිභෝගිකයාගේ සම්පූර්ණ නම ඇතුළත් කරන්න",
  "Enter how many units.": "ඒකක ගණන ඇතුළත් කරන්න.",
  "Enter item name": "භාණ්ඩයේ නම ඇතුළත් කරන්න",
  "Enter quantity": "ප්‍රමාණය ඇතුළත් කරන්න",
  "Enter special note here...": "විශේෂ සටහන මෙහි ඇතුළත් කරන්න...",
  "Enter supplier name": "සැපයුම්කරුගේ නම ඇතුළත් කරන්න",
  "Enter the cost price per unit.": "ඒකකයක පිරිවැය මිල ඇතුළත් කරන්න.",
  "Enter the selling price per unit.": "ඒකකයක විකුණුම් මිල ඇතුළත් කරන්න.",
  "Enter the unit cost.": "ඒකක පිරිවැය ඇතුළත් කරන්න.",
  "Enter your selling price per unit": "ඒකකයක විකුණුම් මිල ඇතුළත් කරන්න",
  "Est. Profit": "ඇස්තමේන්තු ලාභය",
  "Estimated Profit (LKR)": "ඇස්තමේන්තු ලාභය (රු.)",
  "Every prediction shows what pushed it up and what held it back, in plain words.":
      "සෑම අනාවැකියක්ම එය ඉහළ දැමූ සහ පහළ තැබූ හේතු සරල වචනවලින් පෙන්වයි.",
  "Every sale, purchase, expense, deposit and transfer.":
      "සෑම විකුණුමක්ම, මිලදී ගැනීමක්ම, වියදමක්ම, තැන්පතුවක්ම සහ මාරු කිරීමක්ම.",
  "Expected Arrival": "අපේක්ෂිත පැමිණීම",
  "Expected Selling Price (LKR)": "අපේක්ෂිත විකුණුම් මිල (රු.)",
  "Expected arrival:": "අපේක්ෂිත පැමිණීම:",
  "Expected delivery time (Used for Dynamic Safety Stock)": "අපේක්ෂිත බෙදාහැරීමේ කාලය (ආරක්ෂිත තොග ගණනයට)",
  "Expense": "වියදම",
  "Explainable AI": "පැහැදිලි කළ හැකි AI",
  "Explainable, not a black box": "පැහැදිලි කළ හැකියි, රහසක් නොවේ",
  "Failed": "අසාර්ථක",
  "Failed to add bank.": "බැංකුව එක් කළ නොහැකි විය.",
  "Failed to add cash.": "මුදල් එක් කළ නොහැකි විය.",
  "Failed to delete notification": "දැනුම්දීම මැකිය නොහැකි විය",
  "Failed to get recommendations.": "නිර්දේශ ලබාගත නොහැකි විය.",
  "Failed to load": "පූරණය කළ නොහැකි විය",
  "Failed to load report": "වාර්තාව පූරණය කළ නොහැකි විය",
  "Failed to load transaction details.": "ගනුදෙනු විස්තර පූරණය කළ නොහැකි විය.",
  "Failed to load transaction.": "ගනුදෙනුව පූරණය කළ නොහැකි විය.",
  "Failed to mark notification as read": "දැනුම්දීම කියවූ ලෙස සලකුණු කළ නොහැකි විය",
  "Failed to save decision.": "තීරණය සුරැකිය නොහැකි විය.",
  "Failed to save supplier details.": "සැපයුම්කරු විස්තර සුරැකිය නොහැකි විය.",
  "False alarms down from 136 to 19 per 1,000 honest customers":
      "අවංක පාරිභෝගිකයින් 1,000කට වැරදි අනතුරු ඇඟවීම් 136 සිට 19 දක්වා අඩු විය",
  "Feb": "පෙබ",
  "Festival Season": "උත්සව සමය",
  "Festival Season (0/1)": "උත්සව සමය (0/1)",
  "Festival Season (1 = Yes, 0 = No)": "උත්සව සමය (1 = ඔව්, 0 = නැත)",
  "File": "ගොනුව",
  "Final score": "අවසාන ලකුණු",
  "Finance": "මූල්‍ය",
  "Financial Reports": "මූල්‍ය වාර්තා",
  "Financial Statement": "මූල්‍ය ප්‍රකාශය",
  "Financial Summary": "මූල්‍ය සාරාංශය",
  "Fixed delivery fee per shipment": "එක් යැවීමකට ස්ථාවර ගාස්තුව",
  "Flags unusual transactions; CBSL daily limits enforced.":
      "අසාමාන්‍ය ගනුදෙනු හඳුනාගනී; CBSL දෛනික සීමා බලාත්මකයි.",
  "Float / settlement accounts for your agency banking operations.":
      "ඔබේ නියෝජිත බැංකු කටයුතු සඳහා float / පියවීම් ගිණුම්.",
  "Float Ceiling": "float උපරිම සීමාව",
  "Float Floor": "float අවම සීමාව",
  "Float accounts": "float ගිණුම්",
  "Float after": "පසු float",
  "Float after top-up": "පිරවීමෙන් පසු float",
  "Float balance": "float ශේෂය",
  "Float is at": "float ශේෂය",
  "Float top-up": "float පිරවීම",
  "Float will drop below floor — top-up recommended.": "float ශේෂය අවම සීමාවට පහළ යයි — පිරවීම නිර්දේශිතයි.",
  "Float will exceed ceiling — schedule a sweep.":
      "float ශේෂය උපරිම සීමාව ඉක්මවයි — අතිරික්තය බැංකුවට යවන්න.",
  "Floor (100%)": "අවම සීමාව (100%)",
  "Floor:": "අවම සීමාව:",
  "Following it saves about 2.2% of the purchase bill":
      "එය අනුගමනය කිරීමෙන් මිලදී ගැනීමේ බිලෙන් 2.2%ක් පමණ ඉතිරි වේ",
  "Forecast": "පුරෝකථනය",
  "Forgot password?": "මුරපදය අමතකද?",
  "Four AI models read your records. Every result shows why — and what you can do about it.":
      "AI මාදිලි හතරක් ඔබේ වාර්තා කියවයි. සෑම ප්‍රතිඵලයක්ම හේතුව සහ ඔබට කළ හැකි දේ පෙන්වයි.",
  "Four modules, one shop": "මොඩියුල හතරක්, එක කඩයක්",
  "Fresh Milk": "නැවුම් කිරි",
  "From": "සිට",
  "Full Name": "සම්පූර්ණ නම",
  "Full reports →": "සම්පූර්ණ වාර්තා →",
  "Fund Transfer": "අරමුදල් මාරු කිරීම",
  "Galle": "ගාල්ල",
  "Gampaha": "ගම්පහ",
  "General Journal": "සාමාන්‍ය ජර්නලය",
  "General Journal & Reports": "සාමාන්‍ය ජර්නලය සහ වාර්තා",
  "Generated": "සාදන ලද්දේ",
  "Geolocation isn't supported on this browser.": "මෙම browser එකේ ස්ථානය ලබාගැනීමට සහාය නැත.",
  "Get Recommendations": "නිර්දේශ ලබාගන්න",
  "Get Started": "ආරම්භ කරන්න",
  "Get started": "ආරම්භ කරන්න",
  "Good price right now": "දැන් හොඳ මිලක්",
  "Goods Movement": "භාණ්ඩ චලනය",
  "Government market average for": "රජයේ වෙළඳපොළ සාමාන්‍යය:",
  "Gram (g)": "ග්‍රෑම් (g)",
  "Gross Profit": "දළ ලාභය",
  "Grow": "වර්ධනය",
  "HEALTHY": "හොඳ මට්ටමේ",
  "HIGH": "ඉහළ",
  "HKARTI Wholesale Prices": "HKARTI තොග මිල",
  "HKARTI Wholesale Prices ·": "HKARTI තොග මිල ·",
  "HKARTI daily or weekly bulletins · Select multiple files at once":
      "HKARTI දෛනික හෝ සතිපතා නිවේදන · ගොනු කිහිපයක් එකවර තෝරන්න",
  "Hambantota": "හම්බන්තොට",
  "Have an account? ": "ගිණුමක් තිබේද? ",
  "Health": "තත්ත්වය",
  "Healthy": "හොඳ මට්ටමේ",
  "Helping": "උදව් වන",
  "Helping the result ↑": "ප්‍රතිඵලයට උදව් වන ↑",
  "Here's your Lanka-Link today": "අද ඔබේ Lanka-Link",
  "Here's your Lanka-Link today.": "අද ඔබේ Lanka-Link.",
  "High Priority": "ඉහළ ප්‍රමුඛතාව",
  "High monthly expenses eat your profit — look for costs to cut.":
      "ඉහළ මාසික වියදම් ඔබේ ලාභය අඩු කරයි — අඩු කළ හැකි වියදම් සොයන්න.",
  "High spread": "විශාල මිල පරතරය",
  "High volume / urban": "ඉහළ පරිමාව / නාගරික",
  "Higher monthly sales show the business can carry a loan.":
      "ඉහළ මාසික විකුණුම් ව්‍යාපාරයට ණයක් දැරිය හැකි බව පෙන්වයි.",
  "Historical Avg Price Rs": "ඓතිහාසික සාමාන්‍ය මිල",
  "History": "ඉතිහාසය",
  "Holding back": "අඩු කරන",
  "Holding it back ↓": "ප්‍රතිඵලය අඩු කරන ↓",
  "Holding you back": "ඔබව පසුපසට අදින දේ",
  "Hour": "වේලාව",
  "Household & Cleaning": "ගෘහ සහ පිරිසිදු කිරීම්",
  "How confident we are": "අපගේ විශ්වාසය",
  "How far? Show route": "දුර කීයද? මාර්ගය පෙන්වන්න",
  "How it works": "ක්‍රියා කරන ආකාරය",
  "How it works:": "ක්‍රියා කරන ආකාරය:",
  "How sure are these predictions?": "මෙම අනාවැකි කොතරම් විශ්වාසදායකද?",
  "How your data is handled": "ඔබේ දත්ත හසුරුවන ආකාරය",
  "ISO Week": "ISO සතිය",
  "ISO Year": "ISO වර්ෂය",
  "If an account exists, we've sent reset instructions to your inbox.":
      "ගිණුමක් තිබේ නම්, යළි සැකසීමේ උපදෙස් ඔබේ inbox එකට එවා ඇත.",
  "In Business": "ව්‍යාපාරයේ",
  "In stock": "තොගයේ ඇත",
  "Inactive": "අක්‍රිය",
  "Income & Expense Statement": "ආදායම් සහ වියදම් ප්‍රකාශය",
  "Income Statement": "ආදායම් ප්‍රකාශය",
  "Income minus expenses": "ආදායම අඩු කළා වියදම්",
  "Income minus expenses · tap for the statement": "ආදායම අඩු කළා වියදම් · ප්‍රකාශය බලන්න තට්ටු කරන්න",
  "Initial Quantity": "ආරම්භක ප්‍රමාණය",
  "Insufficient cash on hand to pay out this withdrawal.": "මෙම මුදල් ආපසු දීමට අතේ ප්‍රමාණවත් මුදල් නැත.",
  "Insufficient float in the selected bank for this deposit.":
      "තෝරාගත් බැංකුවේ මෙම තැන්පතුවට ප්‍රමාණවත් float ශේෂයක් නැත.",
  "Insufficient float to fund this deposit.": "මෙම තැන්පතුවට ප්‍රමාණවත් float ශේෂයක් නැත.",
  "Inventory": "තොගය",
  "Inventory Item": "තොග භාණ්ඩය",
  "Iso Week": "ISO සතිය",
  "Iso Year": "ISO වර්ෂය",
  "Isolation Forest Flag": "Isolation Forest සලකුණ",
  "Item": "භාණ්ඩය",
  "Item (sale deducts / purchase adds stock)": "භාණ්ඩය (විකුණුම තොගය අඩු කරයි / මිලදී ගැනීම එකතු කරයි)",
  "Item *": "භාණ්ඩය *",
  "Item Delivery Lead Time (Days)": "භාණ්ඩ බෙදාහැරීමේ කාලය (දින)",
  "Item Details": "භාණ්ඩ විස්තර",
  "Item Information": "භාණ්ඩ තොරතුරු",
  "Item Name": "භාණ්ඩයේ නම",
  "Item Name *": "භාණ්ඩයේ නම *",
  "Item Name is required.": "භාණ්ඩයේ නම අවශ්‍යයි.",
  "Item Purchased": "මිලදී ගත් භාණ්ඩය",
  "Item Sold": "විකුණූ භාණ්ඩය",
  "Item name is required.": "භාණ්ඩයේ නම අවශ්‍යයි.",
  "Item name required.": "භාණ්ඩයේ නම අවශ්‍යයි.",
  "Items": "භාණ්ඩ",
  "Items Supplied": "සපයන භාණ්ඩ",
  "Items at or below their reorder level.": "නැවත ඇණවුම් මට්ටමට හෝ ඊට පහළින් ඇති භාණ්ඩ.",
  "Items in this purchase": "මෙම මිලදී ගැනීමේ භාණ්ඩ",
  "Items in this sale": "මෙම විකුණුමේ භාණ්ඩ",
  "Items out of stock": "තොගය අවසන් භාණ්ඩ",
  "Items they carry:": "ඔවුන් සපයන භාණ්ඩ:",
  "Jaffna": "යාපනය",
  "Jan": "ජන",
  "Join Lanka-Link and manage your business": "Lanka-Link හා එක්වී ඔබේ ව්‍යාපාරය කළමනාකරණය කරන්න",
  "Join Lanka-Link and manage your kade.": "Lanka-Link හා එක්වී ඔබේ කඩේ කළමනාකරණය කරන්න.",
  "Joined": "එක්වූ දිනය",
  "Journal": "ජර්නලය",
  "Jul": "ජූලි",
  "Jun": "ජූනි",
  "K-Means clustering groups markets by price level and stability. Buy from green cluster markets to save the most.":
      "K-Means මගින් වෙළඳපොළවල් මිල මට්ටම සහ ස්ථාවරත්වය අනුව කාණ්ඩ කරයි. වැඩිපුරම ඉතිරි කිරීමට කොළ කාණ්ඩයේ වෙළඳපොළවලින් මිලදී ගන්න.",
  "Kalutara": "කළුතර",
  "Kandy": "මහනුවර",
  "Keep daily sales steadier": "දෛනික විකුණුම් වඩා ස්ථාවරව තබාගන්න",
  "Keep every item in stock": "සෑම භාණ්ඩයක්ම තොගයේ තබාගන්න",
  "Kegalle": "කෑගල්ල",
  "Kilinochchi": "කිලිනොච්චි",
  "Kilogram (kg)": "කිලෝග්‍රෑම් (kg)",
  "Kurunegala": "කුරුණෑගල",
  "LKR ": "රු. ",
  "LKR/day": "රු./දිනකට",
  "LOW": "අඩු",
  "LOW ALERT": "float අඩුයි",
  "Lag 1 Price": "සතියකට පෙර මිල",
  "Lag 1 Price (LKR)": "සතියකට පෙර මිල (රු.)",
  "Lag 1 Units": "සතියකට පෙර ඒකක",
  "Lag 1 Units Sold": "සතියකට පෙර විකුණූ ඒකක",
  "Lag 4 Price": "සති 4කට පෙර මිල",
  "Lag 4 Price (LKR)": "සති 4කට පෙර මිල (රු.)",
  "Lag 4 Units": "සති 4කට පෙර ඒකක",
  "Lag 4 Units Sold": "සති 4කට පෙර විකුණූ ඒකක",
  "Lag1 Price": "සතියකට පෙර මිල",
  "Language": "භාෂාව",
  "Last 7 days": "පසුගිය දින 7",
  "Last Received": "අවසන් වරට ලැබුණේ",
  "Last month": "පසුගිය මාසය",
  "Lead Time": "බෙදාහැරීමේ කාලය",
  "Lead time cannot be negative.": "බෙදාහැරීමේ කාලය සෘණ විය නොහැක.",
  "Leave blank for auto (AI)": "ස්වයංක්‍රීය (AI) සඳහා හිස්ව තබන්න",
  "Less:": "අඩු කළා:",
  "Less: Cost of Goods Sold": "අඩු කළා: විකුණූ භාණ්ඩවල පිරිවැය",
  "Less: Expenses": "අඩු කළා: වියදම්",
  "Light mode": "ආලෝක ආකාරය",
  "Likely range": "බොහෝ විට පරාසය",
  "Line Total": "පේළි එකතුව",
  "Linear Regression trained on": "Linear Regression පුහුණු කළේ",
  "List": "ලැයිස්තුව",
  "Liter (l)": "ලීටර් (l)",
  "Live": "සජීවී",
  "Loading admin dashboard...": "පරිපාලක පුවරුව පූරණය වෙමින්...",
  "Loading banks…": "බැංකු පූරණය වෙමින්…",
  "Loading dashboard...": "උපකරණ පුවරුව පූරණය වෙමින්...",
  "Loading inventory...": "තොගය පූරණය වෙමින්...",
  "Loading items...": "භාණ්ඩ පූරණය වෙමින්...",
  "Loading map…": "සිතියම පූරණය වෙමින්…",
  "Loading notifications...": "දැනුම්දීම් පූරණය වෙමින්...",
  "Loading procurement...": "මිලදී ගැනීම් පූරණය වෙමින්...",
  "Loading report...": "වාර්තාව පූරණය වෙමින්...",
  "Loading suppliers...": "සැපයුම්කරුවන් පූරණය වෙමින්...",
  "Loading transaction details...": "ගනුදෙනු විස්තර පූරණය වෙමින්...",
  "Loading transactions...": "ගනුදෙනු පූරණය වෙමින්...",
  "Loading users...": "පරිශීලකයින් පූරණය වෙමින්...",
  "Loading...": "පූරණය වෙමින්...",
  "Loading…": "පූරණය වෙමින්…",
  "Loan Readiness": "ණය සූදානම",
  "Loan limit": "ණය සීමාව",
  "Locating…": "ස්ථානය සොයමින්…",
  "Location": "ස්ථානය",
  "Location is required.": "ස්ථානය අවශ්‍යයි.",
  "Location permission denied.": "ස්ථාන අවසරය ප්‍රතික්ෂේප විය.",
  "Log Out": "ඉවත් වන්න",
  "Low Stock Alerts": "අඩු තොග ඇඟවීම්",
  "Low Stock Items": "තොගය අඩු භාණ්ඩ",
  "Low float": "float අඩුයි",
  "Low volume / rural": "අඩු පරිමාව / ග්‍රාමීය",
  "MEDIUM": "මධ්‍යම",
  "Make 20% more sales each day": "දිනපතා විකුණුම් 20%කින් වැඩි කරන්න",
  "Manage all users →": "සියලු පරිශීලකයින් කළමනාකරණය →",
  "Manage procurement decisions.": "මිලදී ගැනීමේ තීරණ කළමනාකරණය කරන්න.",
  "Manage supplier details.": "සැපයුම්කරු විස්තර කළමනාකරණය කරන්න.",
  "Mannar": "මන්නාරම",
  "Map": "සිතියම",
  "Map search failed": "සිතියම් සෙවීම අසාර්ථකයි",
  "Map search failed — check the internet connection.":
      "සිතියම් සෙවීම අසාර්ථකයි — අන්තර්ජාල සම්බන්ධතාවය පරීක්ෂා කරන්න.",
  "Map search needs the Google Maps key — run with --dart-define-from-file=.env":
      "සිතියම් සෙවීමට Google Maps key එක අවශ්‍යයි — --dart-define-from-file=.env සමඟ run කරන්න",
  "Mar": "මාර්",
  "Margin:": "ආන්තිකය:",
  "Mark Read": "කියවූ ලෙස සලකුණු කරන්න",
  "Mark all read": "සියල්ල කියවූ ලෙස සලකුණු කරන්න",
  "Market Comparison": "වෙළඳපොළ සංසන්දනය",
  "Market Price Data": "වෙළඳපොළ මිල දත්ත",
  "Market Trends": "වෙළඳපොළ ප්‍රවණතා",
  "Market analytics and supplier recommendations.": "වෙළඳපොළ විශ්ලේෂණය සහ සැපයුම්කරු නිර්දේශ.",
  "Matale": "මාතලේ",
  "Matara": "මාතර",
  "May": "මැයි",
  "Medium volume": "මධ්‍යම පරිමාව",
  "Menu": "මෙනුව",
  "Merchant": "වෙළෙන්දා",
  "Merchant Account": "වෙළෙන්දාගේ ගිණුම",
  "Merchant Dashboard": "වෙළෙන්දාගේ උපකරණ පුවරුව",
  "Milliliter (ml)": "මිලිලීටර් (ml)",
  "Minimum 6 characters.": "අවම අක්ෂර 6යි.",
  "Missing:": "අඩුපාඩු:",
  "Models were trained on public and simulated data, so the comparisons are fair but the exact numbers are not real-world guarantees.":
      "මාදිලි පොදු සහ අනුකරණය කළ දත්ත මත පුහුණු කළ නිසා සංසන්දන සාධාරණයි, නමුත් නිශ්චිත අගයන් සැබෑ ලෝකයේ සහතික නොවේ.",
  "Modules": "මොඩියුල",
  "Monaragala": "මොණරාගල",
  "Money": "මුදල්",
  "Money in": "ලැබුණු මුදල්",
  "Money in & out": "මුදල් ලැබීම් සහ යැවීම්",
  "Money out": "ගිය මුදල්",
  "Monthly Expenses (LKR)": "මාසික වියදම් (රු.)",
  "Monthly Expenses Rs": "මාසික වියදම්",
  "Monthly Profit (LKR)": "මාසික ලාභය (රු.)",
  "Monthly Revenue (LKR)": "මාසික ආදායම (රු.)",
  "Monthly Revenue Rs": "මාසික ආදායම",
  "Monthly average prices. Shows which month is cheapest to buy each item.":
      "මාසික සාමාන්‍ය මිල. එක් එක් භාණ්ඩය මිලදී ගැනීමට අඩුම මිල මාසය පෙන්වයි.",
  "Monthly expenses (LKR)": "මාසික වියදම් (රු.)",
  "Monthly profit in this scenario": "මෙම අවස්ථාවේ මාසික ලාභය",
  "Monthly sales (LKR)": "මාසික විකුණුම් (රු.)",
  "Months Active": "ක්‍රියාකාරී මාස",
  "Months Active in Business": "ව්‍යාපාරයේ ක්‍රියාකාරී මාස",
  "Months in business": "ව්‍යාපාරයේ මාස",
  "More monthly profit means you can repay a loan more easily.":
      "වැඩි මාසික ලාභයක් යනු ණයක් පහසුවෙන් ආපසු ගෙවිය හැකි බවයි.",
  "Most expensive:": "වැඩිම මිල:",
  "Most recent transaction": "අවසන් ගනුදෙනුව",
  "Move cash from the shared pool into this float account.":
      "පොදු සංචිතයේ මුදල් මෙම float ගිණුමට මාරු කරන්න.",
  "Move physical cash into this float account.": "අතේ ඇති මුදල් මෙම float ගිණුමට මාරු කරන්න.",
  "Move the sliders to see how your credit score would change. The AI model re-scores your shop.":
      "ඔබේ ණය ලකුණු වෙනස් වන ආකාරය බැලීමට sliders චලනය කරන්න. AI මාදිලිය ඔබේ කඩයට නැවත ලකුණු දෙයි.",
  "Mullaitivu": "මුලතිව්",
  "My Banks": "මගේ බැංකු",
  "NET LOSS": "ශුද්ධ අලාභය",
  "NET PROFIT": "ශුද්ධ ලාභය",
  "Name": "නම",
  "Nearest supplier": "ළඟම සැපයුම්කරු",
  "Net Cash Flow": "ශුද්ධ මුදල් ප්‍රවාහය",
  "Net Cash Flow (LKR)": "ශුද්ධ මුදල් ප්‍රවාහය (රු.)",
  "Net Income / Profit": "ශුද්ධ ආදායම / ලාභය",
  "Net Loss": "ශුද්ධ අලාභය",
  "Net Profit": "ශුද්ධ ලාභය",
  "Net change": "ශුද්ධ වෙනස",
  "New": "නව",
  "New Agency Banking Transaction": "නව නියෝජිත බැංකු ගනුදෙනුවක්",
  "New Decision": "නව තීරණයක්",
  "New Ledger Entry": "නව ලෙජර සටහනක්",
  "New Procurement": "නව මිලදී ගැනීමක්",
  "New Procurement Decision": "නව මිලදී ගැනීමේ තීරණයක්",
  "New Transaction": "නව ගනුදෙනුවක්",
  "New here?": "අලුත්ද?",
  "New here? Create account": "අලුත්ද? ගිණුමක් සාදන්න",
  "New password": "නව මුරපදය",
  "Next 4 wks: LKR": "ඊළඟ සති 4: රු.",
  "Next week": "ලබන සතිය",
  "Next week's demand per item, aware of Avurudu and festivals.":
      "අවුරුදු සහ උත්සව සලකා, එක් එක් භාණ්ඩයට ලබන සතියේ ඉල්ලුම.",
  "Nimal Perera": "නිමල් පෙරේරා",
  "No": "නැත",
  "No banks yet. Add your first float account to start.":
      "තවම බැංකු නැත. ආරම්භ කිරීමට පළමු float ගිණුම එක් කරන්න.",
  "No banks yet. Add your first float account.": "තවම බැංකු නැත. ඔබේ පළමු float ගිණුම එක් කරන්න.",
  "No data for profit / loss.": "ලාභ / අලාභ සඳහා දත්ත නැත.",
  "No data for this range.": "මෙම කාල පරාසයට දත්ත නැත.",
  "No data yet": "තවම දත්ත නැත",
  "No entries this month.": "මෙම මාසයේ සටහන් නැත.",
  "No expenses recorded.": "වියදම් සටහන් කර නැත.",
  "No financial records for this period.": "මෙම කාලයට මූල්‍ය වාර්තා නැත.",
  "No float movements yet.": "තවම float චලනයන් නැත.",
  "No goods movement in this range.": "මෙම කාල පරාසයේ භාණ්ඩ චලනයක් නැත.",
  "No inventory items": "තොග භාණ්ඩ නැත",
  "No inventory items found": "තොග භාණ්ඩ හමු නොවීය",
  "No inventory items yet": "තවම තොග භාණ්ඩ නැත",
  "No inventory items yet.": "තවම තොග භාණ්ඩ නැත.",
  "No items added yet.": "තවම භාණ්ඩ එක් කර නැත.",
  "No items have reached their reorder level.": "කිසිදු භාණ්ඩයක් නැවත ඇණවුම් මට්ටමට පැමිණ නැත.",
  "No items match \"": "ගැළපෙන භාණ්ඩ නැත \"",
  "No items match.": "ගැළපෙන භාණ්ඩ නැත.",
  "No journal entries in this range.": "මෙම කාල පරාසයේ ජර්නල් සටහන් නැත.",
  "No known supplier carries any of these items yet.": "මෙම භාණ්ඩ සපයන සැපයුම්කරුවෙකු තවම නැත.",
  "No known supplier for \"": "සැපයුම්කරුවෙකු නැත \"",
  "No market price data available yet. Admin needs to upload the daily HKARTI price PDF.":
      "තවම වෙළඳපොළ මිල දත්ත නැත. පරිපාලක HKARTI දෛනික මිල PDF එක උඩුගත කළ යුතුයි.",
  "No matches found": "ගැළපීම් හමු නොවීය",
  "No notifications": "දැනුම්දීම් නැත",
  "No notifications yet": "තවම දැනුම්දීම් නැත",
  "No places found.": "ස්ථාන හමු නොවීය.",
  "No procurement records": "මිලදී ගැනීම් වාර්තා නැත",
  "No recent activity yet.": "තවම මෑත ක්‍රියාකාරකම් නැත.",
  "No records for this period.": "මෙම කාලයට වාර්තා නැත.",
  "No records found": "වාර්තා හමු නොවීය",
  "No route found": "මාර්ගයක් හමු නොවීය",
  "No sales data yet": "තවම විකුණුම් දත්ත නැත",
  "No single step would raise your score much — keep recording sales and stock.":
      "කිසිදු එක් පියවරකින් ලකුණු බොහෝ වැඩි නොවේ — විකුණුම් සහ තොග සටහන් කිරීම දිගටම කරන්න.",
  "No supplier has a map location yet.": "තවම කිසිදු සැපයුම්කරුවෙකුට සිතියම් ස්ථානයක් නැත.",
  "No suppliers": "සැපයුම්කරුවන් නැත",
  "No suppliers available": "සැපයුම්කරුවන් නැත",
  "No suppliers yet — add one first, or type a name.":
      "තවම සැපයුම්කරුවන් නැත — මුලින් එකක් එක් කරන්න, නැත්නම් නමක් ටයිප් කරන්න.",
  "No suppliers yet — type a name": "තවම සැපයුම්කරුවන් නැත — නමක් ටයිප් කරන්න",
  "No transactions": "ගනුදෙනු නැත",
  "No transactions recorded yet.": "තවම ගනුදෙනු සටහන් කර නැත.",
  "No transactions yet today.": "අද තවම ගනුදෙනු නැත.",
  "No transactions yet.": "තවම ගනුදෙනු නැත.",
  "No users yet.": "තවම පරිශීලකයින් නැත.",
  "No worries, we'll send you reset instructions.": "කරදර නොවන්න, යළි සැකසීමේ උපදෙස් අපි එවන්නම්.",
  "Not balanced": "සමතුලිත නැත",
  "Not enough data yet to show this.": "මෙය පෙන්වීමට තවම ප්‍රමාණවත් දත්ත නැත.",
  "Not found.": "හමු නොවීය.",
  "Not ready yet": "තවම සූදානම් නැත",
  "Note": "සටහන",
  "Nothing is pulling your score down much right now. 👏": "දැනට කිසිවක් ඔබේ ලකුණු බොහෝ අඩු කරන්නේ නැත. 👏",
  "Notifications": "දැනුම්දීම්",
  "Nov": "නොවැ",
  "Now: LKR": "දැන්: රු.",
  "Nuwara Eliya": "නුවරඑළිය",
  "Oct": "ඔක්",
  "On held-out data the demand forecast is about 22% more accurate than “same as last week”.":
      "පරීක්ෂණ දත්ත මත ඉල්ලුම් පුරෝකථනය “පසුගිය සතිය හා සමානයි” යන්නට වඩා 22%ක් පමණ නිවැරදියි.",
  "One app for the small shop and agency-banking agent: record every sale, know what to restock and when, build a credit record, and keep customers' money safe — with AI that explains itself.":
      "කුඩා කඩයට සහ නියෝජිත බැංකු නියෝජිතයාට එක් යෙදුමක්: සෑම විකුණුමක්ම සටහන් කරන්න, කුමක් කවදා පිරවිය යුතුදැයි දැනගන්න, ණය වාර්තාවක් ගොඩනගන්න, පාරිභෝගිකයින්ගේ මුදල් ආරක්ෂිතව තබාගන්න — තමන්ව පැහැදිලි කරන AI සමඟ.",
  "One ledger, connected decisions": "එක ලෙජරයක්, සම්බන්ධ තීරණ",
  "Opening Float": "ආරම්භක float",
  "Operating Expenses": "මෙහෙයුම් වියදම්",
  "Operations": "මෙහෙයුම්",
  "Optional": "අත්‍යවශ්‍ය නොවේ",
  "Optional notes": "අමතර සටහන් (අවශ්‍ය නම්)",
  "Optional note…": "අමතර සටහනක් (අවශ්‍ය නම්)…",
  "Order Date": "ඇණවුම් දිනය",
  "Order No.": "ඇණවුම් අංකය",
  "Ordered": "ඇණවුම් කළා",
  "Orders": "ඇණවුම්",
  "Other": "වෙනත්",
  "Other Income": "වෙනත් ආදායම",
  "Other suppliers": "වෙනත් සැපයුම්කරුවන්",
  "Out of stock": "තොගය අවසන්",
  "Outstanding debt": "ඉතිරි ණය",
  "Overall cheapest market": "සමස්තයක් ලෙස අඩුම මිල වෙළඳපොළ",
  "Overview": "දළ විශ්ලේෂණය",
  "Owner Capital Injection": "හිමිකරුගේ ප්‍රාග්ධන එකතු කිරීම",
  "PDF preview": "PDF පෙරදසුන",
  "PDF reports are in English.": "PDF වාර්තා ඉංග්‍රීසියෙන් පමණි.",
  "Paid digitally": "ඩිජිටල් ලෙස ගෙවූ",
  "Parsing:": "කියවමින්:",
  "Particulars": "විස්තරය",
  "Password": "මුරපදය",
  "Paying down existing debt improves your score.": "දැනට ඇති ණය අඩු කිරීමෙන් ඔබේ ලකුණු වැඩි වේ.",
  "Payment": "ගෙවීම",
  "Payment Method": "ගෙවීම් ක්‍රමය",
  "Payment Method *": "ගෙවීම් ක්‍රමය *",
  "Pending": "පොරොත්තුවෙන්",
  "Pending Procurement": "පොරොත්තු මිලදී ගැනීම්",
  "Period": "කාලය",
  "Personal Care": "පුද්ගලික සත්කාර",
  "Pick a delivery location below to factor in distance too.":
      "දුර ද සලකා බැලීමට පහතින් බෙදාහැරීමේ ස්ථානයක් තෝරන්න.",
  "Pick a delivery location below to rank by distance too.":
      "දුර අනුව ද පෙළගැස්වීමට පහතින් බෙදාහැරීමේ ස්ථානයක් තෝරන්න.",
  "Pick a delivery location on the map.": "සිතියමේ බෙදාහැරීමේ ස්ථානයක් තෝරන්න.",
  "Please enter a valid Quantity.": "වලංගු ප්‍රමාණයක් ඇතුළත් කරන්න.",
  "Please enter a valid amount.": "වලංගු මුදලක් ඇතුළත් කරන්න.",
  "Please enter a valid email address.": "වලංගු ඊමේල් ලිපිනයක් ඇතුළත් කරන්න.",
  "Please select a category (needed for AI forecasting).": "ප්‍රවර්ගයක් තෝරන්න (AI පුරෝකථනයට අවශ්‍යයි).",
  "Please select a category for AI forecasting.": "AI පුරෝකථනය සඳහා ප්‍රවර්ගයක් තෝරන්න.",
  "Please select a category.": "ප්‍රවර්ගයක් තෝරන්න.",
  "Please specify the source of funds.": "අරමුදල් මූලාශ්‍රය සඳහන් කරන්න.",
  "Points = how much the AI model's score rises if you make that one change.":
      "ලකුණු = ඔබ එම වෙනස පමණක් කළහොත් AI මාදිලියේ ලකුණු වැඩිවන ප්‍රමාණය.",
  "Polonnaruwa": "පොළොන්නරුව",
  "Post Transaction": "ගනුදෙනුව සටහන් කරන්න",
  "Prediction Output": "අනාවැකි ප්‍රතිඵලය",
  "Predictions": "අනාවැකි",
  "Preferences": "මනාපයන්",
  "Preparing…": "සකසමින්…",
  "Price Analytics": "මිල විශ්ලේෂණය",
  "Price Prediction": "මිල අනාවැකිය",
  "Price Variance Pct": "මිල විචලනය",
  "Price difference between cheapest and most expensive market per item.":
      "එක් එක් භාණ්ඩයට අඩුම සහ වැඩිම මිල වෙළඳපොළ අතර මිල වෙනස.",
  "Price score based on": "මිල ලකුණු පදනම",
  "Price trend": "මිල ප්‍රවණතාව",
  "Price velocity index. Fast rising price = high demand. Falling = low demand.":
      "මිල වේග දර්ශකය. වේගයෙන් ඉහළ යන මිල = ඉහළ ඉල්ලුම. පහළ යන = අඩු ඉල්ලුම.",
  "Prices may improve soon": "ඉක්මනින් මිල අඩු විය හැක",
  "Privacy & Security": "පෞද්ගලිකත්වය සහ ආරක්ෂාව",
  "Procument": "සැපයුම්කරු",
  "Procurement": "මිලදී ගැනීම්",
  "Procurement DSS": "මිලදී ගැනීම් තීරණ පද්ධතිය",
  "Procurement Decision": "මිලදී ගැනීමේ තීරණය",
  "Procurement Optimizer": "මිලදී ගැනීම් ප්‍රශස්තකරණය",
  "Procurement Order": "මිලදී ගැනීමේ ඇණවුම",
  "Procurement Orders": "මිලදී ගැනීමේ ඇණවුම්",
  "Procurement Saved": "මිලදී ගැනීම සුරකින ලදී",
  "Profile": "පැතිකඩ",
  "Profit & Loss": "ලාභ අලාභ",
  "Profit & Loss Account": "ලාභ අලාභ ගිණුම",
  "Profit Margin": "ලාභ ආන්තිකය",
  "Profit Margin (%)": "ලාභ ආන්තිකය (%)",
  "Profit Margin Pct": "ලාභ ආන්තිකය",
  "Profit margin": "ලාභ ආන්තිකය",
  "Promote": "උසස් කරන්න",
  "Purchase": "මිලදී ගැනීම",
  "Purchase orders": "මිලදී ගැනීමේ ඇණවුම්",
  "Purchase orders, their suppliers and status.": "මිලදී ගැනීමේ ඇණවුම්, සැපයුම්කරුවන් සහ තත්ත්වය.",
  "Purchase value": "මිලදී ගැනීමේ වටිනාකම",
  "Purchasing": "මිලදී ගැනීම",
  "Puttalam": "පුත්තලම",
  "Qty": "ප්‍රමාණය",
  "Quantity": "ප්‍රමාණය",
  "Quantity *": "ප්‍රමාණය *",
  "Quick Actions": "ඉක්මන් ක්‍රියා",
  "Quick Sell": "ඉක්මන් විකුණුම",
  "ROC-AUC 0.795, tested on later weeks than it learned from.":
      "ROC-AUC 0.795, ඉගෙනගත් සතිවලට පසු සති මත පරීක්ෂා කරන ලදී.",
  "ROC-AUC 0.839 on shops it never saw — 99.9% of the best possible on this data.":
      "කවදාවත් නොදුටු කඩ මත ROC-AUC 0.839 — මෙම දත්ත මත ලබාගත හැකි උපරිමයෙන් 99.9%.",
  "Range total": "පරාසයේ එකතුව",
  "Ranked best first": "හොඳම එක මුලින්",
  "Ratnapura": "රත්නපුර",
  "Ready to apply": "අයදුම් කිරීමට සූදානම්",
  "Ready to run your kade": "ඔබේ කඩේ",
  "Received": "ලැබුණා",
  "Recent Activity": "මෑත ක්‍රියාකාරකම්",
  "Recent Agency Transactions": "මෑත නියෝජිත ගනුදෙනු",
  "Recent Decisions": "මෑත තීරණ",
  "Recent Registrations": "මෑත ලියාපදිංචි කිරීම්",
  "Recent activity": "මෑත ක්‍රියාකාරකම්",
  "Recent growth": "මෑත වර්ධනය",
  "Recommended Suppliers": "නිර්දේශිත සැපයුම්කරුවන්",
  "Record": "සටහන් කරන්න",
  "Record a banking transaction.": "බැංකු ගනුදෙනුවක් සටහන් කරන්න.",
  "Record a deposit, withdrawal, or transfer.": "තැන්පතුවක්, ආපසු ගැනීමක් හෝ මාරු කිරීමක් සටහන් කරන්න.",
  "Record a procurement decision.": "මිලදී ගැනීමේ තීරණයක් සටහන් කරන්න.",
  "Record every sale — more sales per day lifts the score.":
      "සෑම විකුණුමක්ම සටහන් කරන්න — දිනකට වැඩි විකුණුම් ලකුණු ඉහළ නංවයි.",
  "Record income, expense, or payment.": "ආදායම, වියදම හෝ ගෙවීම සටහන් කරන්න.",
  "Record some transactions to try the what-if simulator.":
      "\"මෙහෙම වුණොත්?\" simulator එක භාවිත කිරීමට ගනුදෙනු කිහිපයක් සටහන් කරන්න.",
  "Records": "වාර්තා",
  "Refresh": "නැවුම් කරන්න",
  "Register a new supplier.": "නව සැපයුම්කරුවෙකු ලියාපදිංචි කරන්න.",
  "Reliability": "විශ්වසනීයත්වය",
  "Remittance": "විදේශ ප්‍රේෂණ",
  "Remove": "ඉවත් කරන්න",
  "Remove item": "භාණ්ඩය ඉවත් කරන්න",
  "Rent": "කුලිය",
  "Reorder": "නැවත ඇණවුම",
  "Reorder Level": "නැවත ඇණවුම් මට්ටම",
  "Reorder at:": "නැවත ඇණවුම් මට්ටම:",
  "Repeat the new password": "නව මුරපදය නැවත ඇතුළත් කරන්න",
  "Reports": "වාර්තා",
  "Reports & Export": "වාර්තා සහ අපනයනය",
  "Request a new link": "නව සබැඳියක් ඉල්ලන්න",
  "Required Delivery Date": "අවශ්‍ය බෙදාහැරීමේ දිනය",
  "Required for AI Analytics": "AI විශ්ලේෂණයට අවශ්‍යයි",
  "Required for AI Demand Forecasting": "AI ඉල්ලුම් පුරෝකථනයට අවශ්‍යයි",
  "Required for AI demand forecasting": "AI ඉල්ලුම් පුරෝකථනයට අවශ්‍යයි",
  "Required for deposits (AML record)": "තැන්පතු සඳහා අවශ්‍යයි (AML වාර්තාව)",
  "Reset": "යළි සකසන්න",
  "Reset Password": "මුරපදය යළි සකසන්න",
  "Reset failed. The link may have expired.": "යළි සැකසීම අසාර්ථකයි. සබැඳිය කල් ඉකුත් වී ඇති විය හැක.",
  "Restock": "තොග පුරවන්න",
  "Revenue Per Active Month": "ක්‍රියාකාරී මාසයකට ආදායම",
  "Revenue per Active Month (LKR)": "ක්‍රියාකාරී මාසයකට ආදායම (රු.)",
  "Revenue, costs, and net profit.": "ආදායම, පිරිවැය සහ ශුද්ධ ලාභය.",
  "Rice & Grains": "සහල් සහ ධාන්‍ය",
  "Risk Tier": "අවදානම් මට්ටම",
  "Role": "භූමිකාව",
  "Rolling 4 Mean Units": "පසුගිය සති 4 සාමාන්‍ය ඒකක",
  "Rolling 4-Week Mean Price (LKR)": "පසුගිය සති 4 සාමාන්‍ය මිල (රු.)",
  "Rolling 4-Week Mean Units": "පසුගිය සති 4 සාමාන්‍ය ඒකක",
  "Rolling 4-wk Mean Price": "පසුගිය සති 4 සාමාන්‍ය මිල",
  "Rolling 4-wk Mean Units": "පසුගිය සති 4 සාමාන්‍ය ඒකක",
  "Route from your current location": "ඔබ දැන් ඉන්න තැන සිට මාර්ගය",
  "Rs.": "රු.",
  "Rules and ML together": "නීති සහ ML එකට",
  "Run Prediction": "අනාවැකිය ලබාගන්න",
  "Run your kade": "ඔබේ කඩේ",
  "Running Out": "අවසන් වෙමින්",
  "Running out": "අවසන් වෙමින්",
  "Running out of stock lowers your score — reorder popular items earlier.":
      "තොගය අවසන් වීමෙන් ඔබේ ලකුණු අඩු වේ — ජනප්‍රිය භාණ්ඩ කලින්ම ඇණවුම් කරන්න.",
  "Salary": "වැටුප",
  "Sale": "විකුණුම",
  "Sale failed.": "විකුණුම අසාර්ථකයි.",
  "Sale of Property": "දේපළ විකිණීම",
  "Sales": "විකුණුම්",
  "Sales & Finance": "විකුණුම් සහ මූල්‍ය",
  "Sales Forecast": "විකුණුම් පුරෝකථනය",
  "Sales Volatility": "විකුණුම් උච්චාවචනය",
  "Sales Volatility Index": "විකුණුම් උච්චාවචන දර්ශකය",
  "Sales next week": "ලබන සතියේ විකුණුම්",
  "Sales per day": "දිනකට විකුණුම්",
  "Sales value": "විකුණුම් වටිනාකම",
  "Sales, cost of goods and every expense account.": "විකුණුම්, භාණ්ඩ පිරිවැය සහ සෑම වියදම් ගිණුමක්ම.",
  "Sales, purchases & expenses": "විකුණුම්, මිලදී ගැනීම් සහ වියදම්",
  "Sales, purchases, stock and banking in one digital ledger.":
      "විකුණුම්, මිලදී ගැනීම්, තොග සහ බැංකු කටයුතු එකම ඩිජිටල් ලෙජරයක.",
  "Sample data": "නියැදි දත්ත",
  "Save": "සුරකින්න",
  "Save failed.": "සුරැකීම අසාර්ථකයි.",
  "Save this decision": "මෙම තීරණය සුරකින්න",
  "Saving...": "සුරකිමින්...",
  "Savings": "ඉතිරිකිරීම්",
  "Saving…": "සුරකිමින්…",
  "Score": "ලකුණු",
  "Search a place or address…": "ස්ථානයක් හෝ ලිපිනයක් සොයන්න…",
  "Search by customer, phone, type...": "පාරිභෝගිකයා, දුරකථනය, වර්ගය අනුව සොයන්න...",
  "Search by item or supplier...": "භාණ්ඩය හෝ සැපයුම්කරු අනුව සොයන්න...",
  "Search by name or supplier...": "නම හෝ සැපයුම්කරු අනුව සොයන්න...",
  "Search by name, company, contact...": "නම, සමාගම, සම්බන්ධතා අනුව සොයන්න...",
  "Search by type, category, payment...": "වර්ගය, ප්‍රවර්ගය, ගෙවීම අනුව සොයන්න...",
  "Search item...": "භාණ්ඩය සොයන්න...",
  "Seasonal Patterns": "සෘතුමය රටා",
  "Seasonal demand": "සෘතුමය ඉල්ලුම",
  "Security": "ආරක්ෂාව",
  "Select Category...": "වර්ගය තෝරන්න...",
  "Select a supplier": "සැපයුම්කරුවෙකු තෝරන්න",
  "Select a unit.": "ඒකකයක් තෝරන්න.",
  "Select an item first": "මුලින් භාණ්ඩයක් තෝරන්න",
  "Select an item first.": "මුලින් භාණ්ඩයක් තෝරන්න.",
  "Select an item.": "භාණ්ඩයක් තෝරන්න.",
  "Select an item…": "භාණ්ඩයක් තෝරන්න…",
  "Select category…": "ප්‍රවර්ගය තෝරන්න…",
  "Select date": "දිනය තෝරන්න",
  "Select item": "භාණ්ඩය තෝරන්න",
  "Select multiple files at once — system processes them automatically":
      "ගොනු කිහිපයක් එකවර තෝරන්න — පද්ධතිය ඒවා ස්වයංක්‍රීයව සකසයි",
  "Select source": "මූලාශ්‍රය තෝරන්න",
  "Select the arrival date.": "පැමිණෙන දිනය තෝරන්න.",
  "Select unit": "ඒකකය තෝරන්න",
  "Selected Supplier": "තෝරාගත් සැපයුම්කරු",
  "Selling Price per Unit (LKR)": "ඒකකයක විකුණුම් මිල (රු.)",
  "Sending...": "යවමින්...",
  "Sep": "සැප්",
  "Service Fee": "සේවා ගාස්තුව",
  "Service Fee (LKR)": "සේවා ගාස්තුව (රු.)",
  "Service Fees": "සේවා ගාස්තු",
  "Set a new password": "නව මුරපදයක් සකසන්න",
  "Set new password": "නව මුරපදය සකසන්න",
  "Set your shop location to see the road route.": "මාර්ගය බැලීමට ඔබේ කඩේ ස්ථානය සකසන්න.",
  "Set your shop location: use your location or click the map.":
      "ඔබේ කඩේ ස්ථානය සකසන්න: ඔබේ ස්ථානය භාවිත කරන්න හෝ සිතියම මත ක්ලික් කරන්න.",
  "Setting 'Received' adds all items to inventory as batches":
      "'ලැබුණා' ලෙස සැකසූ විට සියලු භාණ්ඩ කාණ්ඩ ලෙස තොගයට එකතු වේ",
  "Settings": "සැකසුම්",
  "Shelf Life Days": "කල් තබාගත හැකි දින",
  "Should I Buy?": "මිලදී ගත යුතුද?",
  "Sign In": "පිවිසෙන්න",
  "Sign Out": "ඉවත් වන්න",
  "Sign in": "පිවිසෙන්න",
  "Sign in to your Lanka-Link account": "ඔබේ Lanka-Link ගිණුමට පිවිසෙන්න",
  "Sign in to your account": "ඔබේ ගිණුමට පිවිසෙන්න",
  "Sign out": "ඉවත් වන්න",
  "Signed in as": "පිවිසී ඇත්තේ",
  "Signing in...": "පිවිසෙමින්...",
  "Signing in…": "පිවිසෙමින්…",
  "Simple predictions based on your recent activity, updated automatically. Green means something is helping you; red means it's holding you back.":
      "ඔබේ මෑත ක්‍රියාකාරකම් මත පදනම් වූ සරල අනාවැකි, ස්වයංක්‍රීයව යාවත්කාලීන වේ. කොළ පාට යනු ඔබට උදව් වන දෙයක්; රතු පාට යනු ඔබව පසුපසට අදින දෙයක්.",
  "Smart Inventory": "ස්මාර්ට් තොග කළමනාකරණය",
  "Smart Merchant Platform": "ස්මාර්ට් වෙළෙන්දන් වේදිකාව",
  "Smart Procurement": "ස්මාර්ට් මිලදී ගැනීම්",
  "Smart stock replenishment decision engine (Buy Now vs. Wait).":
      "ස්මාර්ට් තොග පිරවීමේ තීරණ පද්ධතිය (දැන් ගන්න ද රැඳී සිටින්න ද).",
  "Snacks & Sweets": "කෙටි කෑම සහ රසකැවිලි",
  "Sold": "විකුණූ",
  "Something went wrong. Please try again.": "යමක් වැරදුණා. නැවත උත්සාහ කරන්න.",
  "Source of Funds": "අරමුදල් මූලාශ්‍රය",
  "Source of Funds *": "අරමුදල් මූලාශ්‍රය *",
  "Source of funds is required for deposits.": "තැන්පතු සඳහා අරමුදල් මූලාශ්‍රය අවශ්‍යයි.",
  "Source:": "මූලාශ්‍රය:",
  "Special Note": "විශේෂ සටහන",
  "Specify Source of Funds": "අරමුදල් මූලාශ්‍රය සඳහන් කරන්න",
  "Specify Source of Funds *": "අරමුදල් මූලාශ්‍රය සඳහන් කරන්න *",
  "Spices & Cooking Essentials": "කුළුබඩු සහ ඉවුම් පිහුම් අවශ්‍යතා",
  "Spread: ±": "පරතරය: ±",
  "Start: LKR": "ආරම්භය: රු.",
  "Status": "තත්ත්වය",
  "Steady stock and records build a credit-readiness score.":
      "ස්ථාවර තොගය සහ වාර්තා ණය සූදානම් ලකුණු ගොඩනගයි.",
  "Stock": "තොගය",
  "Stock & batches": "තොග සහ කාණ්ඩ",
  "Stock & purchasing": "තොග සහ මිලදී ගැනීම්",
  "Stock 28 · Reorder 28 (≈23/week forecast)": "තොගය 28 · නැවත ඇණවුම 28 (සතියට ≈23 පුරෝකථනය)",
  "Stock Alerts": "තොග ඇඟවීම්",
  "Stock Report": "තොග වාර්තාව",
  "Stock is added automatically": "තොගය ස්වයංක්‍රීයව එකතු වේ",
  "Stock is deducted automatically": "තොගය ස්වයංක්‍රීයව අඩු වේ",
  "Stock levels, batches and low-stock alerts.": "තොග මට්ටම්, කාණ්ඩ සහ අඩු තොග ඇඟවීම්.",
  "Stock low — restock needed.": "තොගය අඩුයි — පිරවිය යුතුයි.",
  "Stock value": "තොග වටිනාකම",
  "Stock:": "තොගය:",
  "Stockout Rate": "තොග අවසන් වීමේ අනුපාතය",
  "Stockout Rate (0 - 1)": "තොග අවසන් වීමේ අනුපාතය (0 - 1)",
  "Suggested from": "යෝජනා කළේ",
  "Summary": "සාරාංශය",
  "Supplier": "සැපයුම්කරු",
  "Supplier Directory": "සැපයුම්කරු නාමාවලිය",
  "Supplier Name": "සැපයුම්කරුගේ නම",
  "Supplier Name *": "සැපයුම්කරුගේ නම *",
  "Supplier Name is required.": "සැපයුම්කරුගේ නම අවශ්‍යයි.",
  "Supplier Payment": "සැපයුම්කරු ගෙවීම",
  "Supplier name is required.": "සැපයුම්කරුගේ නම අවශ්‍යයි.",
  "Supplier:": "සැපයුම්කරු:",
  "Suppliers": "සැපයුම්කරුවන්",
  "Suppliers by distance": "දුර අනුව සැපයුම්කරුවන්",
  "Suppliers for": "සැපයුම්කරුවන්:",
  "Suppliers on the map": "සිතියමේ සැපයුම්කරුවන්",
  "Suppliers, purchase orders and delivery lead times.":
      "සැපයුම්කරුවන්, මිලදී ගැනීමේ ඇණවුම් සහ බෙදාහැරීමේ කාලය.",
  "Switch between light and dark theme": "ආලෝක සහ අඳුරු ආකාර අතර මාරු වන්න",
  "Switch to dark": "අඳුරු ආකාරයට මාරු වන්න",
  "Switch to light": "ආලෝක ආකාරයට මාරු වන්න",
  "System Notifications": "පද්ධති දැනුම්දීම්",
  "System Revenue": "පද්ධති ආදායම",
  "System-wide overview — users, financials, agency banking, and alerts.":
      "පද්ධතියේ සමස්ත දළ විශ්ලේෂණය — පරිශීලකයින්, මූල්‍ය, නියෝජිත බැංකුකරණය සහ ඇඟවීම්.",
  "Table": "වගුව",
  "Take 20% more payments digitally (card, QR, bank)":
      "ගෙවීම් 20%ක් වැඩිපුර ඩිජිටල් ලෙස ගන්න (කාඩ්, QR, බැංකු)",
  "Tap + to add one.": "එකක් එක් කිරීමට + ඔබන්න.",
  "Tap on the map or search to pick the delivery location":
      "බෙදාහැරීමේ ස්ථානය තෝරීමට සිතියම මත තට්ටු කරන්න හෝ සොයන්න",
  "Tested against simple methods": "සරල ක්‍රම සමඟ පරීක්ෂා කර ඇත",
  "This cannot be undone.": "මෙය ආපසු හැරවිය නොහැක.",
  "This looks different from your usual pattern — worth a quick check.":
      "මෙය ඔබේ සාමාන්‍ය රටාවට වඩා වෙනස් — ඉක්මනින් පරීක්ෂා කිරීම හොඳයි.",
  "This measure is lowering your score.": "මෙය ඔබේ ලකුණු අඩු කරයි.",
  "This month": "මෙම මාසය",
  "This reset link is invalid or incomplete.": "මෙම යළි සැකසීමේ සබැඳිය වලංගු නැත හෝ අසම්පූර්ණයි.",
  "This transaction looks different from your usual pattern — worth a quick check.":
      "මෙම ගනුදෙනුව ඔබේ සාමාන්‍ය රටාවට වඩා වෙනස් — ඉක්මනින් පරීක්ෂා කිරීම හොඳයි.",
  "This year": "මෙම වර්ෂය",
  "Time in business": "ව්‍යාපාරයේ කාලය",
  "Time in business counts — keep recording, the score grows with your history.":
      "ව්‍යාපාරයේ කාලය වැදගත් — සටහන් කිරීම දිගටම කරන්න, ඔබේ ඉතිහාසය සමඟ ලකුණු වැඩි වේ.",
  "Time of transaction": "ගනුදෙනු වේලාව",
  "Tip: You can click on the map and pick the exact location":
      "ඉඟිය: සිතියම මත ක්ලික් කර නිවැරදි ස්ථානය තෝරාගත හැක",
  "To": "දක්වා",
  "To restock": "තොග පිරවීමට",
  "Today": "අද",
  "Today's Commission": "අද කොමිස්",
  "Today's Transactions": "අද ගනුදෙනු",
  "Today's Volume": "අද පරිමාව",
  "Toggle light or dark mode": "ආලෝක හෝ අඳුරු ආකාරයට මාරු කරන්න",
  "Top up": "පුරවන්න",
  "Top-up Amount (LKR)": "පිරවීමේ මුදල (රු.)",
  "Top-up failed.": "පිරවීම අසාර්ථකයි.",
  "Total": "එකතුව",
  "Total Available Quantity:": "මුළු ලබාගත හැකි ප්‍රමාණය:",
  "Total Bought": "මුළු මිලදී ගැනීම්",
  "Total Cash": "මුළු මුදල්",
  "Total Commission": "මුළු කොමිස්",
  "Total Cost": "මුළු පිරිවැය",
  "Total Cost (LKR)": "මුළු පිරිවැය (රු.)",
  "Total Credit": "මුළු බැර",
  "Total Credit:": "මුළු බැර:",
  "Total Debit": "මුළු හර",
  "Total Debit:": "මුළු හර:",
  "Total Expense": "මුළු වියදම",
  "Total Float": "මුළු float",
  "Total Float (all banks)": "මුළු float (සියලු බැංකු)",
  "Total Income": "මුළු ආදායම",
  "Total Items:": "මුළු භාණ්ඩ:",
  "Total Quantity": "මුළු ප්‍රමාණය",
  "Total Quantity:": "මුළු ප්‍රමාණය:",
  "Total Revenue": "මුළු ආදායම",
  "Total Revenue / Sales": "මුළු ආදායම / විකුණුම්",
  "Total Sold": "මුළු විකුණුම්",
  "Total Stock Value": "මුළු තොග වටිනාකම",
  "Total Users": "මුළු පරිශීලකයින්",
  "Total files": "මුළු ගොනු",
  "Total revenue": "මුළු ආදායම",
  "Track stock levels and items.": "තොග මට්ටම් සහ භාණ්ඩ නිරීක්ෂණය කරන්න.",
  "Trading & Profit and Loss Account": "වෙළඳ සහ ලාභ අලාභ ගිණුම",
  "Trading Account": "වෙළඳ ගිණුම",
  "Transaction": "ගනුදෙනුව",
  "Transaction Type": "ගනුදෙනු වර්ගය",
  "Transaction Type *": "ගනුදෙනු වර්ගය *",
  "Transaction record": "ගනුදෙනු වාර්තාව",
  "Transaction record not found.": "ගනුදෙනු වාර්තාව හමු නොවීය.",
  "Transaction size": "ගනුදෙනුවේ ප්‍රමාණය",
  "Transaction type": "ගනුදෙනු වර්ගය",
  "Transactions": "ගනුදෙනු",
  "Transactions Report": "ගනුදෙනු වාර්තාව",
  "Transfer": "මාරු කිරීම",
  "Trial Balance": "පරීක්ෂණ ශේෂය",
  "Trincomalee": "ත්‍රිකුණාමලය",
  "Try Again": "නැවත උත්සාහ කරන්න",
  "Try a different search term.": "වෙනත් සෙවුම් පදයක් උත්සාහ කරන්න.",
  "Txn Type": "ගනුදෙනු වර්ගය",
  "Type": "වර්ගය",
  "Type:": "වර්ගය:",
  "Unit": "ඒකකය",
  "Unit Cost": "ඒකක පිරිවැය",
  "Unit Cost (LKR)": "ඒකක පිරිවැය (රු.)",
  "Unit Cost (LKR) *": "ඒකක පිරිවැය (රු.) *",
  "Unit Cost per Unit (LKR)": "ඒකකයක පිරිවැය (රු.)",
  "Unit Cost × Quantity": "ඒකක පිරිවැය × ප්‍රමාණය",
  "Unit Price": "ඒකක මිල",
  "Unit Price (LKR)": "ඒකක මිල (රු.)",
  "Unit price cannot be negative.": "ඒකක මිල සෘණ විය නොහැක.",
  "Units": "ඒකක",
  "Units Bought": "මිලදී ගත් ඒකක",
  "Units Sold": "විකුණූ ඒකක",
  "Units bought": "මිලදී ගත් ඒකක",
  "Units sold": "විකුණූ ඒකක",
  "Units sold and bought per item, with their value.":
      "එක් එක් භාණ්ඩයේ විකුණූ සහ මිලදී ගත් ඒකක සහ ඒවායේ වටිනාකම.",
  "Unread (": "නොකියවූ (",
  "Unread Notifications": "නොකියවූ දැනුම්දීම්",
  "Unsupervised Anomaly Score": "අසාමාන්‍යතා ලකුණ",
  "Unusual location": "අසාමාන්‍ය ස්ථානය",
  "Unusual transaction": "අසාමාන්‍ය ගනුදෙනුව",
  "Update": "යාවත්කාලීන කරන්න",
  "Update Item": "භාණ්ඩය යාවත්කාලීන කරන්න",
  "Update Supplier": "සැපයුම්කරු යාවත්කාලීන කරන්න",
  "Update Transaction": "ගනුදෙනුව යාවත්කාලීන කරන්න",
  "Update agency banking transaction records and details.": "නියෝජිත බැංකු ගනුදෙනු විස්තර යාවත්කාලීන කරන්න.",
  "Update decision details.": "තීරණ විස්තර යාවත්කාලීන කරන්න.",
  "Update supplier details.": "සැපයුම්කරු විස්තර යාවත්කාලීන කරන්න.",
  "Update the details.": "විස්තර යාවත්කාලීන කරන්න.",
  "Update transaction details.": "ගනුදෙනු විස්තර යාවත්කාලීන කරන්න.",
  "Upload HKARTI PDFs to enable ML analytics.": "ML විශ්ලේෂණ සක්‍රිය කිරීමට HKARTI PDF උඩුගත කරන්න.",
  "Upload Price PDFs": "මිල PDF උඩුගත කරන්න",
  "Upload complete": "උඩුගත කිරීම සම්පූර්ණයි",
  "Upload more files": "තවත් ගොනු උඩුගත කරන්න",
  "Upload the HKARTI daily wholesale price PDF. Merchants will use this data for supplier recommendations.":
      "HKARTI දෛනික තොග මිල PDF එක උඩුගත කරන්න. වෙළෙන්දන් මෙම දත්ත සැපයුම්කරු නිර්දේශ සඳහා භාවිත කරයි.",
  "Upload the daily price bulletin from the Hector Kobbekaduwa Agrarian Research and Training Institute. Once uploaded, merchants can open Procurement from their sidebar and run supplier recommendations — their prices will be benchmarked against the government wholesale average you uploaded here.":
      "හෙක්ටර් කොබ්බෑකඩුව ගොවිකටයුතු පර්යේෂණ හා පුහුණු කිරීමේ ආයතනයේ දෛනික මිල නිවේදනය උඩුගත කරන්න. උඩුගත කළ පසු, වෙළෙන්දන්ට පැති තීරුවෙන් මිලදී ගැනීම් විවෘත කර සැපයුම්කරු නිර්දේශ ලබාගත හැක — ඔවුන්ගේ මිල ඔබ මෙහි උඩුගත කළ රජයේ තොග සාමාන්‍යය සමඟ සංසන්දනය කෙරේ.",
  "Uploaded": "උඩුගත කළ",
  "Used for daily transaction-count limits (max 5/day per NIC)":
      "දෛනික ගනුදෙනු ගණන් සීමා සඳහා (එක් ජා.හැ.අ.කට දිනකට උපරිම 5)",
  "Used for daily transaction-count limits (max 5/day)": "දෛනික ගනුදෙනු ගණන් සීමා සඳහා (දිනකට උපරිම 5)",
  "User Breakdown": "පරිශීලක බෙදීම",
  "User Management": "පරිශීලක කළමනාකරණය",
  "Vavuniya": "වවුනියාව",
  "Very uneven daily sales look risky — steadier sales help.":
      "ඉතා අසමාන දෛනික විකුණුම් අවදානම් ලෙස පෙනේ — ස්ථාවර විකුණුම් උදව් වේ.",
  "View": "බලන්න",
  "View Alerts": "ඇඟවීම් බලන්න",
  "View alerts and manage notification history": "ඇඟවීම් බලන්න සහ දැනුම්දීම් ඉතිහාසය කළමනාකරණය කරන්න",
  "View all agency transactions →": "සියලු නියෝජිත ගනුදෙනු බලන්න →",
  "View all items →": "සියලු භාණ්ඩ බලන්න →",
  "View all transactions →": "සියලු ගනුදෙනු බලන්න →",
  "View all →": "සියල්ල බලන්න →",
  "View and edit your account details": "ඔබේ ගිණුම් විස්තර බලන්න සහ සංස්කරණය කරන්න",
  "View every report, preview it as a PDF and download it as PDF or Excel.":
      "සියලු වාර්තා බලන්න, PDF ලෙස පෙරදසුන බලන්න, PDF හෝ Excel ලෙස බාගන්න.",
  "View →": "බලන්න →",
  "Volume": "පරිමාව",
  "We couldn't load your forecasts. Please try again in a moment.":
      "ඔබේ පුරෝකථන පූරණය කළ නොහැකි විය. මොහොතකින් නැවත උත්සාහ කරන්න.",
  "Weekday": "සතියේ දිනය",
  "Weekday (0-6)": "සතියේ දිනය (0-6)",
  "Weekend Sales Share (0 - 1)": "සති අන්ත විකුණුම් කොටස (0 - 1)",
  "Weekend Share": "සති අන්ත කොටස",
  "Weekly demand forecast for every item that sells.": "විකිණෙන සෑම භාණ්ඩයකටම සතිපතා ඉල්ලුම් පුරෝකථනය.",
  "Welcome back": "නැවත සාදරයෙන් පිළිගනිමු",
  "What if": "මෙහෙම වුණොත්",
  "What if…?": "මෙහෙම වුණොත්…?",
  "What is holding your credit score back, and the steps that would raise it most.":
      "ඔබේ ණය ලකුණු අඩු කරන්නේ කුමක්ද, සහ ඒවා වැඩිපුරම ඉහළ නංවන පියවර.",
  "What you record once feeds every insight. The demand forecast sets when to restock, and steady stock improves your credit score.":
      "ඔබ එක් වරක් සටහන් කරන දේ සියලු අවබෝධයන්ට යොදා ගැනේ. ඉල්ලුම් පුරෝකථනය තොග පිරවිය යුතු කාලය තීරණය කරයි, ස්ථාවර තොගය ඔබේ ණය ලකුණු වැඩි කරයි.",
  "What's affecting this": "මෙයට බලපාන්නේ කුමක්ද",
  "Which float account funds this transaction": "මෙම ගනුදෙනුවට මුදල් සපයන float ගිණුම",
  "Why ranked #": "ස්ථානය # වීමට හේතුව",
  "Why you can trust it": "ඔබට විශ්වාස කළ හැක්කේ ඇයි",
  "Withdrawal": "ආපසු ගැනීම",
  "Yes": "ඔව්",
  "You": "ඔබ",
  "You're all caught up.": "ඔබ සියල්ල බලා ඇත.",
  "Your Business Forecasts": "ඔබේ ව්‍යාපාර පුරෝකථන",
  "Your Forecasts": "ඔබේ පුරෝකථන",
  "Your action plan": "ඔබේ ක්‍රියාකාරී සැලැස්ම",
  "Your business health meets key lending criteria for loan approvals.":
      "ඔබේ ව්‍යාපාරය ණය අනුමැතිය සඳහා ප්‍රධාන නිර්ණායක සපුරයි.",
  "Your business health meets key lending criteria — up to":
      "ඔබේ ව්‍යාපාරය ප්‍රධාන ණය නිර්ණායක සපුරයි — උපරිම",
  "Your business overview — finances, stock and procurement.":
      "ඔබේ ව්‍යාපාර දළ විශ්ලේෂණය — මූල්‍ය, තොග සහ මිලදී ගැනීම්.",
  "Your business this week": "මෙම සතියේ ඔබේ ව්‍යාපාරය",
  "Your full name": "ඔබේ සම්පූර්ණ නම",
  "Your password": "ඔබේ මුරපදය",
  "Your password has been updated. Please sign in with your new password.":
      "ඔබේ මුරපදය යාවත්කාලීන විය. නව මුරපදයෙන් පිවිසෙන්න.",
  "Your payout as agent": "නියෝජිතයා ලෙස ඔබට ලැබෙන මුදල",
  "Your session has expired. Please sign in again.": "ඔබේ සැසිය කල් ඉකුත් විය. නැවත පිවිසෙන්න.",
  "Your session is protected": "ඔබේ සැසිය ආරක්ෂිතයි",
  "Your shop": "ඔබේ කඩේ",
  "Your shop location is set — click the map to change it.":
      "ඔබේ කඩේ ස්ථානය සකසා ඇත — වෙනස් කිරීමට සිතියම මත ක්ලික් කරන්න.",
  "Your vendors": "ඔබේ සැපයුම්කරුවන්",
  "balance_inquiry": "ශේෂ විමසීම",
  "bank": "බැංකුව",
  "box": "පෙට්ටිය",
  "by road": "මාර්ගයෙන්",
  "cancelled": "අවලංගුයි",
  "carton": "කාටනය",
  "cash": "මුදල්",
  "cash_deposit": "මුදල් තැන්පතුව",
  "cash_withdrawal": "මුදල් ආපසු ගැනීම",
  "currently in stock": "දැනට තොගයේ ඇත",
  "data pts": "දත්ත ලක්ෂ්‍ය",
  "days": "දින",
  "days of data.": "දින ගණනක දත්ත මතයි.",
  "days ·": "දින ·",
  "deposit": "තැන්පතුව",
  "digital": "ඩිජිටල්",
  "e.g. 1": "උදා. 1",
  "e.g. 1100.00": "උදා. 1100.00",
  "e.g. 199012345678": "උදා. 199012345678",
  "e.g. 2": "උදා. 2",
  "e.g. 3 (for AI reorder buffer)": "උදා. 3 (AI නැවත ඇණවුම් ගණනයට)",
  "e.g. 3 (used for safety stock)": "උදා. 3 (ආරක්ෂිත තොග ගණනයට)",
  "e.g. 8001234567": "උදා. 8001234567",
  "e.g. ABC Holdings (Pvt) Ltd": "උදා. ABC හෝල්ඩිංග්ස් (පුද්.) සමාගම",
  "e.g. ABC Traders": "උදා. ABC ට්‍රේඩර්ස්",
  "e.g. Bank of Ceylon": "උදා. ලංකා බැංකුව",
  "e.g. Colombo": "උදා. කොළඹ",
  "e.g. Nimal Perera": "උදා. නිමල් පෙරේරා",
  "e.g. Panguwa, Thambana, Monaragala District": "උදා. පංගුව, තඹාන, මොණරාගල දිස්ත්‍රික්කය",
  "e.g. Rice 5 kg bag": "උදා. සහල් 5 kg මල්ල",
  "e.g. Rice 5kg": "උදා. සහල් 5kg",
  "e.g. SLIIT, New Kandy Rd, Malabe": "උදා. SLIIT, නව මහනුවර පාර, මාලබේ",
  "expense": "වියදම",
  "fund_transfer": "අරමුදල් මාරු කිරීම",
  "high": "ඉහළ",
  "in stock)": "තොගයේ ඇත)",
  "items": "භාණ්ඩ",
  "items ·": "භාණ්ඩ ·",
  "low": "අඩු",
  "medium": "මධ්‍යම",
  "money in": "ලැබුණු මුදල්",
  "money out": "ගිය මුදල්",
  "more without a saved map location": "ක් සිතියම් ස්ථානයක් නොමැතිව",
  "mos": "මාස",
  "ordered": "ඇණවුම් කළා",
  "out of 100": "100න්",
  "pending": "පොරොත්තුවෙන්",
  "pick one to auto-fill cost & unit": "පිරිවැය සහ ඒකකය ස්වයංක්‍රීයව පිරවීමට එකක් තෝරන්න",
  "purchase": "මිලදී ගැනීම",
  "received": "ලැබුණා",
  "reserved for daily ops": "දෛනික කටයුතු සඳහා වෙන් කර ඇත",
  "risk tier": "අවදානම් මට්ටම",
  "running low.": "අඩු වෙමින් පවතී.",
  "sale": "විකුණුම",
  "smarter.": "ස්මාර්ට්ව පවත්වන්න.",
  "smarter?": "ස්මාර්ට්ව පවත්වන්න සූදානම්ද?",
  "supplier comparison": "සැපයුම්කරු සංසන්දනය",
  "to restock": "තොග පිරවීමට",
  "transfer": "මාරු කිරීම",
  "unit": "ඒකකය",
  "units": "ඒකක",
  "units / next week": "ඒකක / ලබන සතිය",
  "units / next wk": "ඒකක / ලබන සතිය",
  "units · ≈ Rs 70,900": "ඒකක · ≈ රු. 70,900",
  "© 2026 Lanka-Link · Smart Merchant Support Platform":
      "© 2026 Lanka-Link · ස්මාර්ට් වෙළෙන්දන් සහාය වේදිකාව",
  "· LKR": "· රු.",
  "· Qty": "· ප්‍රමාණය",
  "· Reorder:": "· නැවත ඇණවුම:",
  "× LKR": "× රු.",
  "— LKR": "— රු.",
  "— No bank (skip float) —": "— බැංකුවක් නැත (float මඟහරින්න) —",
  "— Select source —": "— මූලාශ්‍රය තෝරන්න —",
  "— Select —": "— තෝරන්න —",
  "— — predicted (next 4 weeks)": "— — අනාවැකිය (ඊළඟ සති 4)",
  "← All Inventory": "← සියලු තොගය",
  "← All Models": "← සියලු මාදිලි",
  "← Back": "← ආපසු",
  "↻ Refresh": "↻ නැවුම් කරන්න",
  "≈ Rs": "≈ රු.",
  "⏳ Wait": "⏳ රැඳී සිටින්න",
  "▲ stock increased (bought more than sold) · ▼ stock decreased (sold more than bought)":
      "▲ තොගය වැඩි විය (විකුණුවාට වඩා මිලදී ගත්තා) · ▼ තොගය අඩු විය (මිලදී ගත්තාට වඩා විකුණුවා)",
  "⚠ Looks unusual": "⚠ අසාමාන්‍ය ලෙස පෙනේ",
  "⚠ Running low — reorder needed": "⚠ අඩු වෙමින් — නැවත ඇණවුම් කළ යුතුයි",
  "⚠️ Low Stock Alerts": "⚠️ අඩු තොග ඇඟවීම්",
  "⚠️ Needs Improvement": "⚠️ දියුණු කළ යුතුයි",
  "⚠️ Needs work": "⚠️ දියුණු කළ යුතුයි",
  "⚡ Quick Sell": "⚡ ඉක්මන් විකුණුම",
  "✅ Ready": "✅ සූදානම්",
  "✓ Adequate": "✓ ප්‍රමාණවත්",
  "✓ Daily price bulletins": "✓ දෛනික මිල නිවේදන",
  "✓ In stock": "✓ තොගයේ ඇත",
  "✓ Looks normal": "✓ සාමාන්‍යයි",
  "✓ Normal": "✓ සාමාන්‍යයි",
  "✓ Ready to Apply": "✓ අයදුම් කිරීමට සූදානම්",
  "✓ Up to 200 files": "✓ ගොනු 200ක් දක්වා",
  "✓ Weekly bulletins": "✓ සතිපතා නිවේදන",
  "⬇ Export CSV": "⬇ CSV ලෙස අපනයනය",
  "🏆 Best overall": "🏆 සමස්තයක් ලෙස හොඳම",
  "🏛 Using HKARTI market prices": "🏛 HKARTI වෙළඳපොළ මිල භාවිත කරයි",
  "👥 Manage Users": "👥 පරිශීලකයින් කළමනාකරණය",
  "💰 Cheapest": "💰 අඩුම මිල",
  "📊 Income Statement": "📊 ආදායම් ප්‍රකාශය",
  "📍 Nearest": "📍 ළඟම",
  "📍 Use My Location": "📍 මගේ ස්ථානය භාවිත කරන්න",
  "🚚 Fastest": "🚚 වේගවත්ම",
  "🚨 Check needed": "🚨 පරීක්ෂා කළ යුතුයි",
  "🚩 Reorder now": "🚩 දැන් ඇණවුම් කරන්න",
  "🛒 Buy": "🛒 මිලදී ගන්න",
  "🛡️ All clear": "🛡️ සියල්ල හොඳයි",
  "🟢 Best match 🟡 Cheapest 🔴 Other suppliers 🔵 Delivery location":
      "🟢 වඩාත් ගැළපෙන 🟡 අඩුම මිල 🔴 වෙනත් සැපයුම්කරුවන් 🔵 බෙදාහැරීමේ ස්ථානය",
  "🟢 Best overall for \"": "🟢 සමස්තයක් ලෙස හොඳම \"",
};
