"use client";

import { useEffect, useState } from "react";
import Link from "next/link";
import { useParams, useRouter } from "next/navigation";

import PageHeader from "@/components/common/PageHeader";
import Button from "@/components/ui/Button";
import Card from "@/components/ui/Card";
import StatusBadge from "@/components/common/StatusBadge";
import LoadingSpinner from "@/components/common/LoadingSpinner";
import { procurementApi } from "@/services/api/procurement.api";

export default function ProcurementDetailPage() {
  const params = useParams();
  const router = useRouter();

  const procurementId = params?.procurementId;

  const [item, setItem] = useState(null);
  const [loading, setLoading] = useState(true);
  const [updatingStatus, setUpdatingStatus] = useState(false);

  useEffect(() => {
    if (!procurementId) return;

    setLoading(true);

    procurementApi
      .getById(procurementId)
      .then((data) => setItem(data))
      .catch(() => setItem(null))
      .finally(() => setLoading(false));
  }, [procurementId]);

  async function updateStatus(status) {
    if (!procurementId) return;

    setUpdatingStatus(true);

    try {
      const updated = await procurementApi.update(procurementId, { status });
      setItem(updated);
    } catch (err) {
      alert(err.message || "Failed to update status");
    } finally {
      setUpdatingStatus(false);
    }
  }

  async function deleteDecision() {
    if (!confirm("Delete this procurement decision?")) return;

    try {
      await procurementApi.delete(procurementId);
      router.push("/dashboard/procurement");
    } catch (err) {
      alert(err.message || "Failed to delete decision");
    }
  }

  return (
    <div className="page-container">
      <PageHeader
        title="Procurement Decision Details"
        description="Research decision record generated by the smart procurement DSS."
        action={
          <Link href="/dashboard/procurement">
            <Button variant="secondary">← Back</Button>
          </Link>
        }
      />

      {loading ? (
        <LoadingSpinner />
      ) : !item ? (
        <Card>
          <p className="text-slate-500">
            Decision not found. ID: {procurementId}
          </p>
        </Card>
      ) : (
        <Card className="max-w-3xl">
          <div className="mb-5 flex flex-col gap-3 sm:flex-row sm:items-start sm:justify-between">
            <div>
              <h2 className="font-outfit text-xl font-bold text-slate-900">
                {item.item_name}
              </h2>
              <p className="mt-1 text-sm text-slate-500">ID: {item.id}</p>
            </div>

            <StatusBadge status={item.status} />
          </div>

          <div className="grid gap-4 md:grid-cols-2">
            <Info label="Current Quantity" value={item.current_quantity} />
            <Info label="Reorder Level" value={item.reorder_level} />
            <Info
              label="Recommended Quantity"
              value={item.recommended_quantity}
            />
            <Info
              label="Supplier Score"
              value={item.supplier_score}
            />
            <Info
              label="Recommended Supplier"
              value={item.recommended_supplier_name || "No supplier"}
            />
            <Info
              label="Decision Type"
              value={item.decision_type}
            />
          </div>

          <div className="mt-5 rounded-xl bg-primary/5 px-4 py-3">
            <p className="text-xs font-semibold uppercase tracking-wide text-primary">
              Decision Reason
            </p>
            <p className="mt-1 text-sm text-slate-700">
              {item.decision_reason}
            </p>
          </div>

          <div className="mt-5 flex flex-wrap gap-2">
            <Button
              variant="secondary"
              disabled={updatingStatus}
              onClick={() => updateStatus("approved")}
            >
              Approve
            </Button>

            <Button
              variant="secondary"
              disabled={updatingStatus}
              onClick={() => updateStatus("completed")}
            >
              Mark Completed
            </Button>

            <Button
              variant="secondary"
              disabled={updatingStatus}
              onClick={() => updateStatus("rejected")}
            >
              Reject
            </Button>

            <Button variant="danger" onClick={deleteDecision}>
              Delete
            </Button>
          </div>

          <div className="mt-5 rounded-xl bg-slate-50 p-4">
            <pre className="overflow-auto whitespace-pre-wrap text-xs text-slate-600">
              {JSON.stringify(item, null, 2)}
            </pre>
          </div>
        </Card>
      )}
    </div>
  );
}

function Info({ label, value }) {
  return (
    <div className="rounded-xl border border-slate-200 bg-slate-50 px-4 py-3">
      <p className="text-xs font-semibold uppercase tracking-wide text-slate-500">
        {label}
      </p>
      <p className="mt-1 font-medium text-slate-900">{value ?? "-"}</p>
    </div>
  );
}